import {useEffect,useMemo,useState} from 'react'
import {api,venueWorkflowApi} from './api'
import type {OwnerBookingRow,User,Venue,VenueRequest} from './api'
import './AdminDashboard.css'

const roleLabel=(role:string)=>role==='admin'?'แอดมิน':role==='owner'?'เจ้าของสนาม':'ผู้ใช้'
const statusLabel=(status:string)=>{const x=status.toUpperCase();return x==='CONFIRMED'?'ยืนยันแล้ว':x==='CANCELLED'?'ยกเลิกแล้ว':x==='COMPLETED'?'เสร็จสิ้น':x==='EXPIRED'?'หมดเวลา':x==='IN_PROGRESS'?'กำลังใช้งาน':x==='UPCOMING'?'กำลังจะถึง':status}
const dateLabel=(date:string)=>new Intl.DateTimeFormat('th-TH',{dateStyle:'medium',timeZone:'Asia/Bangkok'}).format(new Date(`${date}T00:00:00+07:00`))
const displayStatus=(b:OwnerBookingRow,now:number)=>{if(String(b.status).toUpperCase()==='CANCELLED')return 'CANCELLED';const start=new Date(`${b.booking_date}T${b.start_time}:00+07:00`).getTime();const end=new Date(`${b.booking_date}T${b.end_time}:00+07:00`).getTime();if(now<start)return 'UPCOMING';if(now<end)return 'IN_PROGRESS';return 'COMPLETED'}

export default function AdminDashboard({currentUserId}:{currentUserId?:number}){
 const [venues,setVenues]=useState<Venue[]>([]),[bookings,setBookings]=useState<OwnerBookingRow[]>([])
 const [users,setUsers]=useState<User[]>([]),[venueRequests,setVenueRequests]=useState<VenueRequest[]>([]),[reviewing,setReviewing]=useState<number|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[saving,setSaving]=useState<number|null>(null),[savingVenue,setSavingVenue]=useState<number|null>(null),[bookingFilter,setBookingFilter]=useState('all'),[userFilter,setUserFilter]=useState('all'),[now,setNow]=useState(()=>Date.now()),[loading,setLoading]=useState(true)
 useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),30000);return()=>window.clearInterval(timer)},[])
 const filteredBookings=useMemo(()=>{const sorted=bookings.slice().sort((a,b)=>`${a.booking_date}T${a.start_time}`.localeCompare(`${b.booking_date}T${b.start_time}`));if(bookingFilter==='all')return sorted.reverse();return sorted.filter(b=>displayStatus(b,now)===bookingFilter).reverse()},[bookings,bookingFilter,now])
 const load=async()=>{setLoading(true);setError('');try{const [v,b,u,r]=await Promise.all([api.ownerVenues(),api.ownerBookings(),api.adminUsers(),venueWorkflowApi.adminVenueRequests()]);setVenues(v);setBookings(b);setUsers(u);setVenueRequests(r)}catch(e){setError(e instanceof Error?e.message:'โหลดข้อมูลไม่สำเร็จ')}finally{setLoading(false)}}
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);const onFocus=()=>void load();const onVisible=()=>{if(document.visibilityState==='visible')void load()};window.addEventListener('focus',onFocus);document.addEventListener('visibilitychange',onVisible);const interval=window.setInterval(()=>void load(),30000);return ()=>{window.clearTimeout(timer);window.removeEventListener('focus',onFocus);document.removeEventListener('visibilitychange',onVisible);window.clearInterval(interval)}},[])
 const confirmed=useMemo(()=>bookings.filter(b=>String(b.status).toUpperCase()==='CONFIRMED'),[bookings])
 const upcoming=useMemo(()=>bookings.filter(b=>displayStatus(b,now)==='UPCOMING').length,[bookings,now])
 const active=useMemo(()=>bookings.filter(b=>displayStatus(b,now)==='IN_PROGRESS').length,[bookings,now])
 const total=useMemo(()=>confirmed.reduce((sum,b)=>sum+Number(b.total_price||0),0),[confirmed])
 const owners=useMemo(()=>users.filter(u=>u.role==='owner'),[users])
 const reviewVenue=async(id:number,action:'approve'|'request_changes'|'reject')=>{const venue=venueRequests.find(v=>v.id===id);if(!venue)return;let note='';if(action!=='approve'){note=window.prompt(action==='reject'?'เหตุผลที่ไม่อนุมัติ':'สิ่งที่เจ้าของสนามต้องแก้ไข')?.trim()||'';if(!note){setError('กรุณาระบุเหตุผลก่อนดำเนินการ');return}}setReviewing(id);setError('');setMessage('');try{const v=await venueWorkflowApi.adminVenueReview(id,action,note);setVenueRequests(x=>x.filter(item=>item.id!==v.id));setVenues(x=>x.map(item=>item.id===v.id?v:item));setMessage(action==='approve'?`อนุมัติ ${v.name} แล้ว สนามพร้อมเปิดรับจอง`:action==='request_changes'?`ส่งรายการแก้ไขให้ ${v.name} แล้ว`:`ไม่อนุมัติ ${v.name} แล้ว`);window.dispatchEvent(new Event('porsball:data-changed'))}catch(e){setError(e instanceof Error?e.message:'ตรวจสอบสนามไม่สำเร็จ')}finally{setReviewing(null)}}
 const changeRole=async(id:number,role:string)=>{setSaving(id);setError('');setMessage('');try{const u=await api.updateAdminRole(id,role);setUsers(x=>x.map(item=>item.id===u.id?u:item));setMessage(`อัปเดตสิทธิ์ ${u.name} เป็น ${roleLabel(u.role)} แล้ว`);window.dispatchEvent(new Event('porsball:data-changed'))}catch(e){setError(e instanceof Error?e.message:'เปลี่ยนสิทธิ์ไม่สำเร็จ')}finally{setSaving(null)}}
 const changeVenueOwner=async(id:number,value:string)=>{setSavingVenue(id);setError('');setMessage('');try{const v=await api.assignVenueOwner(id,value?Number(value):null);setVenues(x=>x.map(item=>item.id===v.id?v:item));setMessage(value?`กำหนด ${v.name} ให้เจ้าของสนามเรียบร้อยแล้ว`:`นำเจ้าของออกจาก ${v.name} แล้ว`);window.dispatchEvent(new Event('porsball:data-changed'))}catch(e){setError(e instanceof Error?e.message:'กำหนดเจ้าของสนามไม่สำเร็จ')}finally{setSavingVenue(null)}}
 return <section className="page admin-page">
  <div className="section-head"><div><p className="eyebrow">ADMIN CONTROL</p><h1>แผงควบคุมแอดมิน</h1><p>จัดการภาพรวมของผู้ใช้ สนาม และรายการจองจากจุดเดียว</p></div><button type="button" className="link" onClick={()=>void load()} disabled={loading} aria-label="รีเฟรชข้อมูลแอดมิน" aria-busy={loading}>{loading?'กำลังโหลด...':'รีเฟรชข้อมูล'}</button></div>
  {error&&<div className="panel admin-error" role="alert" aria-live="assertive">{error}</div>}
  {message&&<div className="panel admin-success" role="status" aria-live="polite">{message}</div>}
  <div className="panel admin-section venue-review-section"><div className="section-head"><div><h2>สนามรอตรวจสอบ</h2><p>ตรวจข้อมูลก่อนเปิดสนามให้ลูกค้าจองใน PorsBall</p></div><strong>{venueRequests.filter(v=>v.review_status==='pending_review').length} รายการ</strong></div>{venueRequests.length?<div className="admin-table">{venueRequests.map(v=><div className="admin-row venue-review-row" key={v.id}><div><b>{v.name}</b><small>เจ้าของ: {v.owner_name||'-'} · {v.owner_email||'-'}</small><small>{v.area} · {v.field_types} · ฿{v.price_per_hour.toLocaleString()}/ชม.</small><small>{v.address}</small></div><span className={`admin-status review-${v.review_status}`}>{v.review_status==='pending_review'?'รอตรวจสอบ':v.review_status==='changes_requested'?'รอแก้ไข':v.review_status==='rejected'?'ไม่อนุมัติ':'อนุมัติแล้ว'}</span>{v.review_note&&<small className="review-note">หมายเหตุ: {v.review_note}</small>}{v.review_status==='pending_review'&&<div className="review-actions"><button type="button" className="primary" disabled={reviewing===v.id} onClick={()=>void reviewVenue(v.id,'approve')}>อนุมัติ</button><button type="button" disabled={reviewing===v.id} onClick={()=>void reviewVenue(v.id,'request_changes')}>ขอให้แก้ไข</button><button type="button" className="danger" disabled={reviewing===v.id} onClick={()=>void reviewVenue(v.id,'reject')}>ไม่อนุมัติ</button></div>}</div>)}</div>:<div className="admin-empty">ยังไม่มีสนามรอตรวจสอบ</div>}</div>
  <div className="admin-stats"><div className="panel"><span>สนามทั้งหมด</span><b>{venues.length}</b></div><div className="panel"><span>ผู้ใช้ในระบบ</span><b>{users.length}</b></div><div className="panel"><span>กำลังใช้งาน</span><b>{active}</b></div><div className="panel"><span>กำลังจะถึง</span><b>{upcoming}</b></div><div className="panel"><span>ยอดจองที่ยืนยัน</span><b>฿{total.toLocaleString()}</b></div></div>
  <div className="panel admin-section"><div className="section-head"><div><h2>จัดการผู้ใช้</h2><p>ตรวจสอบบัญชีและกำหนดบทบาทการใช้งาน</p></div></div>
   <div className="admin-role-filters" role="tablist" aria-label="กรองผู้ใช้ตามบทบาท">{[['all','ทั้งหมด'],['player','ผู้ใช้'],['owner','เจ้าของสนาม'],['admin','แอดมิน']].map(([value,label])=><button key={value} type="button" className={userFilter===value?'active':''} role="tab" aria-selected={userFilter===value} aria-controls="admin-user-results" onClick={()=>setUserFilter(value)}>{label}</button>)}</div>
   <div id="admin-user-results" className="admin-table" role="tabpanel" aria-live="polite">{users.filter(u=>userFilter==='all'||u.role===userFilter).map(u=><div className="admin-row" key={u.id}><div><b>{u.name}</b><small>{u.email}</small></div><div><span>แต้ม {u.points} · ชนะ {u.wins} · แพ้ {u.losses}</span></div><select value={u.role} disabled={saving===u.id||u.id===currentUserId} aria-label={`บทบาทของ ${u.name}`} aria-busy={saving===u.id} title={u.id===currentUserId?'บัญชีแอดมินที่กำลังใช้งานไม่สามารถลดสิทธิ์ได้':''} onChange={e=>void changeRole(u.id,e.target.value)}><option value="player">{roleLabel('player')}</option><option value="owner">{roleLabel('owner')}</option><option value="admin">{roleLabel('admin')}</option></select></div>)}</div>
   {!users.filter(u=>userFilter==='all'||u.role===userFilter).length&&<div className="admin-empty">ไม่พบผู้ใช้ในหมวดนี้</div>}
  </div>
  <div className="panel admin-section"><div className="section-head"><div><h2>สนามทั้งหมด</h2><p>กำหนดหรือเปลี่ยนเจ้าของสนามได้จากหน้านี้</p></div></div>{venues.length?<div className="admin-table">{venues.map(v=><div className="admin-row" key={v.id}><div><b>{v.name}</b><small>{v.area} · {v.field_types}</small></div><strong>฿{v.price_per_hour.toLocaleString()}/ชม.</strong><select value={v.owner_id??''} disabled={savingVenue===v.id} aria-label={`เจ้าของสนาม ${v.name}`} aria-busy={savingVenue===v.id} title="เลือกเจ้าของสนาม" onChange={e=>void changeVenueOwner(v.id,e.target.value)}><option value="">ยังไม่มีเจ้าของ</option>{owners.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></div>)}</div>:<div className="admin-empty">ยังไม่มีข้อมูลสนาม</div>}</div>
  <div className="panel admin-section"><div className="section-head"><div><h2>รายการจองล่าสุด</h2><p>ตรวจสอบการใช้งานสนามทั้งหมด</p></div></div>{bookings.length>0&&<div className="admin-booking-filters" role="tablist" aria-label="กรองรายการจอง">{[['all','ทั้งหมด'],['UPCOMING','กำลังจะถึง'],['IN_PROGRESS','กำลังใช้งาน'],['COMPLETED','เสร็จสิ้น'],['CANCELLED','ยกเลิกแล้ว']].map(([value,label])=><button key={value} type="button" className={bookingFilter===value?'active':''} role="tab" aria-selected={bookingFilter===value} aria-controls="admin-booking-results" onClick={()=>setBookingFilter(value)}>{label}</button>)}</div>}{bookings.length?filteredBookings.length?<div id="admin-booking-results" className="admin-table" role="tabpanel" aria-live="polite">{filteredBookings.slice(0,20).map(b=>{const status=displayStatus(b,now);return <div className="admin-row" key={b.id}><div><b>{b.venue_name}</b><small>{dateLabel(b.booking_date)} · {b.start_time}–{b.end_time}</small></div><div><b>{b.user_name}</b><small>{b.user_email}</small></div><div className="sr-only">หมายเลขการจอง {b.id}</div><strong>฿{b.total_price.toLocaleString()}</strong><span className={`admin-status status-${status.toLowerCase()}`}>{statusLabel(status)}</span></div>})}</div>:<div className="admin-empty">ไม่มีรายการในหมวดนี้</div>:<div className="admin-empty">ยังไม่มีรายการจอง</div>}</div>
 </section>
}
