import {useEffect,useState} from 'react'
import AdminDashboard from './AdminDashboard'
import OwnerDashboard from './OwnerDashboard'
import OwnerBookings from './OwnerBookings'
import './App.css'
import Manage from './Manage'
import {api} from './api'
import type {Venue,Slot,Match,MatchPlayer,User,BookingRow,SplitBill,Notification} from './api'

type HomeProps={query:string;setQuery:(s:string)=>void;venues:Venue[];matches:Match[];select:(v:Venue)=>void;nav:(s:string)=>void;venueError:boolean;retry:()=>void}
export default function App(){
 const splitPath=window.location.pathname.match(/^\/split\/([a-f0-9]{48})$/i)
 const [tab,setTab]=useState('home'),[notifications,setNotifications]=useState<Notification[]>([]),[showNotifications,setShowNotifications]=useState(false),[venues,setVenues]=useState<Venue[]>([]),[matches,setMatches]=useState<Match[]>([]),[query,setQuery]=useState(''),[selected,setSelected]=useState<Venue|null>(null),[user,setUser]=useState<User|null>(null),[auth,setAuth]=useState(false),[venueError,setVenueError]=useState(false)
 const refreshMatches=()=>api.matches().then(setMatches).catch(console.error)
 const loadVenues=()=>api.venues(query).then(v=>{setVenues(v);setVenueError(false)}).catch(()=>{setVenues([]);setVenueError(true)})
 useEffect(()=>{void api.venues(query).then(v=>{setVenues(v);setVenueError(false)}).catch(()=>{setVenues([]);setVenueError(true)})},[query])
 useEffect(()=>{void api.matches().then(setMatches).catch(console.error)},[tab])
 useEffect(()=>{const onChanged=()=>{void api.matches().then(setMatches).catch(console.error)};window.addEventListener('porsball:data-changed',onChanged);return()=>window.removeEventListener('porsball:data-changed',onChanged)},[])
 useEffect(()=>{let cancelled=false;const expired=()=>{localStorage.removeItem('porsball_token');if(!cancelled){setUser(null);setNotifications([]);setShowNotifications(false);setAuth(true)}};window.addEventListener('porsball:auth-expired',expired);if(!localStorage.getItem('porsball_token'))return()=>window.removeEventListener('porsball:auth-expired',expired);const loadNotifications=()=>{api.notifications().then(x=>{if(!cancelled)setNotifications(x)}).catch(()=>{});};api.me().then(x=>{if(!cancelled)setUser(x)}).catch(()=>localStorage.removeItem('porsball_token'));loadNotifications();const timer=window.setInterval(loadNotifications,30000);const onFocus=()=>loadNotifications();window.addEventListener('focus',onFocus);return()=>{cancelled=true;window.clearInterval(timer);window.removeEventListener('focus',onFocus);window.removeEventListener('porsball:auth-expired',expired)}},[])
 const nav=(x:string)=>setTab(x)
 if(splitPath)return <SplitGuestPage token={splitPath[1]}/>
 return <div className="app"><header><div className="brand"><b>Pors</b><span>Ball</span> ⚽</div><div className="location">📍 กรุงเทพมหานคร, ประเทศไทย</div><div style={{position:'relative'}}><button className="login" onClick={()=>user?setShowNotifications(!showNotifications):setAuth(true)}>{user?'🔔'+(notifications.filter(n=>!n.read).length?` ${notifications.filter(n=>!n.read).length}`:''):'เข้าสู่ระบบ'}</button>{showNotifications&&user&&<NotificationPanel items={notifications} setItems={setNotifications} close={()=>setShowNotifications(false)}/>}</div></header><main>
 {tab==='home'&&<Home query={query} setQuery={setQuery} venues={venues} matches={matches} select={setSelected} nav={nav} venueError={venueError} retry={loadVenues}/>} {tab==='matches'&&<Matches matches={matches} refresh={refreshMatches} user={user}/>} {tab==='profile'&&<Profile user={user} onLogout={()=>{localStorage.removeItem('porsball_token');setUser(null);setNotifications([]);setShowNotifications(false);setTab('home')}}/>} {tab==='bookings'&&<Bookings/>} {tab==='manage'&&(user?.role==='admin'?<AdminDashboard currentUserId={user.id}/>:user?.role==='owner'?<><OwnerDashboard/><OwnerBookings/></>:<Manage user={user}/>)} {tab==='create'&&<CreateMatchPage user={user}/>}
 </main>{selected&&<Booking v={selected} close={()=>setSelected(null)}/>} {auth&&<Auth close={()=>setAuth(false)} onUser={setUser}/>}
 <nav className="bottom"><Nav active={tab==='home'} icon="⌂" text="หน้าแรก" click={()=>nav('home')}/><Nav active={tab==='matches'} icon="⚽" text="หาเพื่อน" click={()=>nav('matches')}/>{(user?.role==='owner'||user?.role==='admin')&&<Nav active={tab==='manage'} icon={String.fromCodePoint(9881)} text={user?.role==='admin'?'แอดมิน':'จัดการสนาม'} click={()=>nav('manage')}/>}<Nav active={tab==='bookings'} icon="📅" text="การจอง" click={()=>nav('bookings')}/><Nav active={tab==='profile'} icon="👤" text="โปรไฟล์" click={()=>nav('profile')}/></nav></div>
}
function NotificationPanel({items,setItems,close}:{items:Notification[];setItems:(x:Notification[])=>void;close:()=>void}){const unread=items.filter(n=>!n.read);const read=async(id:number)=>{await api.readNotification(id);setItems(items.map(n=>n.id===id?{...n,read:1}:n))};const all=async()=>{await api.readAllNotifications();setItems(items.map(n=>({...n,read:1})))};useEffect(()=>{const onKey=(e:globalThis.KeyboardEvent)=>{if(e.key==='Escape')close()};document.addEventListener('keydown',onKey);return()=>document.removeEventListener('keydown',onKey)},[close]);return <div className="notification-panel" role="dialog" aria-label="การแจ้งเตือน"><div className="notification-head"><b>การแจ้งเตือน</b>{unread.length>0&&<button onClick={all}>อ่านทั้งหมด</button>}<button onClick={close} aria-label="ปิดการแจ้งเตือน">×</button></div>{items.length?items.map(n=><button className={n.read?'notification read':'notification'} key={n.id} onClick={()=>!n.read&&read(n.id)}><b>{n.title}</b><span>{n.message}</span><small>{new Date(n.created_at+'Z').toLocaleString('th-TH')}</small></button>):<div className="notification-empty">ยังไม่มีการแจ้งเตือน</div>}</div>}
function Nav(p:{active:boolean;icon:string;text:string;click:()=>void}){return <button className={p.active?'navitem active':'navitem'} onClick={p.click}><strong>{p.icon}</strong><span>{p.text}</span></button>}
function Home({query,setQuery,venues,matches,select,nav,venueError,retry}:HomeProps){const [filter,setFilter]=useState('all');const filtered=venues.filter(v=>filter==='all'||(filter==='roof'&&!!v.roof)||(filter==='5v5'&&/5v5/i.test(v.field_types))||(filter==='7v7'&&/7v7/i.test(v.field_types))||(filter==='11v11'&&/11v11/i.test(v.field_types)));return <><section className="hero"><div><p className="eyebrow">⚽ จองสนามแบบเรียลไทม์</p><h1>วันนี้จะเตะที่ไหนดี?</h1><p className="sub">ค้นหาสนามใกล้คุณ เปิดนัดหาเพื่อน และหารค่าบอลให้จบในที่เดียว</p><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหาสนาม, โซน, หรือสถานที่"/><button>ค้นหา</button></div></div><div className="hero-ball">⚽</div></section><section><div className="section-head"><h2>สนามใกล้คุณ</h2></div><div className="chips"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>ทั้งหมด</button><button className={filter==='5v5'?'active':''} onClick={()=>setFilter('5v5')}>5v5</button><button className={filter==='7v7'?'active':''} onClick={()=>setFilter('7v7')}>7v7</button><button className={filter==='11v11'?'active':''} onClick={()=>setFilter('11v11')}>11v11</button><button className={filter==='roof'?'active':''} onClick={()=>setFilter('roof')}>หลังคา</button></div><div className="pitch-grid">{filtered.map(v=><PitchCard key={v.id} v={v} click={()=>select(v)}/>)}</div>{!venueError&&venues.length>0&&!filtered.length&&<div className="panel">ไม่พบสนามที่ตรงกับตัวกรองนี้ ลองเลือกตัวกรองอื่น</div>}{venueError?<div className="panel"><b>ไม่สามารถเชื่อมต่อเซิร์ฟเวอร์</b><p>กรุณาตรวจสอบการเชื่อมต่อ แล้วลองใหม่อีกครั้ง</p><button className="confirm" onClick={retry}>ลองอีกครั้ง</button></div>:!venues.length&&<div className="panel">ไม่พบสนามที่ค้นหา</div>}</section><section className="match-section"><div className="section-head"><div><h2>⚽ นัดที่กำลังหาคน</h2><p>ข้อมูลจากระบบจริง</p></div><button className="link" onClick={()=>nav('matches')}>ดูทั้งหมด →</button></div><div className="match-grid">{matches.length?matches.slice(0,3).map(m=><MatchCard key={m.id} m={m}/>):<div className="panel home-empty-match"><b>ยังไม่มีนัดที่เปิดรับ</b><p>เมื่อมีคนเปิดนัดหาเพื่อน นัดจะแสดงที่นี่</p></div>}</div></section></>}
function PitchCard({v,click}:{v:Venue;click:()=>void}){return <article className="pitch-card" role="button" tabIndex={0} aria-label={`ดูรอบว่าง ${v.name}`} onClick={click} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();click()}}}><div className="pitch-photo"><span>⚽</span><small>⭐</small></div><div className="pitch-body"><div className="rating">★ {v.rating.toFixed(1)}</div><h3>{v.name}</h3><p>{v.area}  •  {v.field_types}</p><div className="card-foot"><b>฿{v.price_per_hour.toLocaleString()}<em>/ชม.</em></b><button type="button" onClick={e=>{e.stopPropagation();click()}}>ดูรอบว่าง</button></div></div></article>}
function localDateTime(date:string,time:string){return new Date(`${date}T${time}:00+07:00`)}
function todayISO(){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const y=parts.find(p=>p.type==='year')?.value||'';const m=parts.find(p=>p.type==='month')?.value||'';const d=parts.find(p=>p.type==='day')?.value||'';return `${y}-${m}-${d}`}
function bookingState(date:string,start:string,end:string){const now=new Date(),from=localDateTime(date,start),to=localDateTime(date,end);if(now>=to)return 'expired';if(now>=from)return 'active';return 'upcoming'}
function MatchCard({m}:{m:Match}){const end=m.end_time||m.start_time;const state=bookingState(m.match_date,m.start_time,end);return <article className="match-card"><div className="match-icon">⚽</div><div><h3>{m.title}</h3><p>{m.match_date}  •  {m.start_time}–{end}  •  {m.venue_name}</p><div className="avatars">👥 {m.players}/{m.max_players} คน</div></div><b>{state==='expired'?'หมดเวลา':state==='active'?'กำลังใช้งาน':`฿${m.fee}/คน`}</b></article>}
function Booking({v,close}:{v:Venue;close:()=>void}){const [date,setDate]=useState(todayISO()),[slots,setSlots]=useState<Slot[]>([]),[slot,setSlot]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');useEffect(()=>{setSlot('');setError('');api.slots(v.id,date).then(x=>{setSlots(x.slots);const now=new Date();const first=x.slots.find(s=>s.available&&localDateTime(date,s.end)>now);setSlot(first?.start||'')}).catch(()=>{setSlots([]);setError('ไม่สามารถโหลดรอบสนามได้ กรุณาลองใหม่อีกครั้ง')})},[v.id,date]);const confirm=async()=>{if(!slot){setError('กรุณาเลือกเวลาที่ต้องการจอง');return}if(!localStorage.getItem('porsball_token')){setError('กรุณาเข้าสู่ระบบก่อนจองสนาม');return}const chosenEnd=localDateTime(date,`${String(Number(slot.slice(0,2))+1).padStart(2,'0')}:00`);if(chosenEnd<=new Date()){setSlot('');setError('เวลานี้เลยเวลาจองแล้ว กรุณาเลือกเวลาใหม่');return}setBusy(true);try{await api.book(v.id,date,slot,`${String(Number(slot.slice(0,2))+1).padStart(2,'0')}:00`,v.price_per_hour);window.dispatchEvent(new Event('porsball:data-changed'));close()}catch(e){setError(e instanceof Error?e.message:'จองไม่สำเร็จ')}finally{setBusy(false)}};return <div className="modal"><div className="booking"><button className="close" onClick={close}>×</button><div className="booking-photo">⚽</div><div className="booking-content"><div className="rating">★ {v.rating.toFixed(1)}</div><h2>{v.name}</h2><p>{v.area}  •  {v.field_types}{v.roof?'  •  หลังคา':''}</p><h3>เลือกวันที่</h3><input type="date" min={todayISO()} value={date} onChange={e=>setDate(e.target.value)}/><h3>เลือกเวลา</h3><div className="slots">{slots.map(s=>{const slotStart=localDateTime(date,s.start),past=slotStart<=new Date(),canBook=s.available&&!past;return <button disabled={!canBook} className={slot===s.start?'selected':''} onClick={()=>canBook&&setSlot(s.start)} key={s.start}>{s.start}<small>{past?'เลยเวลาจอง':s.available?'ว่าง':'เต็ม'}</small></button>})}</div>{error&&<div className="auth-error" role="alert">{error}</div>}<div className="summary"><span>{slot||'ยังไม่ได้เลือกเวลา'}</span><b>฿{v.price_per_hour.toLocaleString()}</b></div><button className="confirm" disabled={!slot||busy} onClick={confirm}>{busy?'กำลังจอง...':'ยืนยันการจอง →'}</button></div></div></div>}
function Matches({matches,refresh,user}:{matches:Match[];refresh:()=>void;user:User|null}){return <section className="page"><p className="eyebrow">COMMUNITY</p><h1>หาเพื่อนมาเตะด้วยกัน</h1><p>เลือกนัดจากข้อมูลในระบบ แล้วกดเข้าร่วม</p>{matches.length?matches.map(m=><MatchJoin key={m.id} m={m} refresh={refresh} user={user}/>):<div className="panel"><b>ตอนนี้ยังไม่มีนัดที่เปิดรับ</b><p>ลองกลับมาใหม่อีกครั้ง หรือสร้างนัดจากการจองสนามของคุณ</p></div>}</section>}
function MatchJoin({m,refresh,user}:{m:Match;refresh:()=>void;user:User|null}){
 const [busy,setBusy]=useState(false),[players,setPlayers]=useState<MatchPlayer[]>([]),[show,setShow]=useState(false),[status,setStatus]=useState('')
 const isOwner=!!user&&user.id===m.creator_id
 const end=m.end_time||m.start_time
 const state=bookingState(m.match_date,m.start_time,end)
 const loadPlayers=async()=>{try{const r=await api.players(m.id);setPlayers(r.players)}catch{setPlayers([])}}
 useEffect(()=>{let cancelled=false;api.players(m.id).then(r=>{if(!cancelled)setPlayers(r.players)}).catch(()=>{if(!cancelled)setPlayers([])});return()=>{cancelled=true}},[m.id])
 const join=async()=>{if(!localStorage.getItem('porsball_token')){setStatus('กรุณาเข้าสู่ระบบก่อนเข้าร่วมนัด');return}setStatus('');setBusy(true);try{await api.join(m.id);await loadPlayers();refresh();setStatus('เข้าร่วมนัดแล้ว ✓')}catch(e){setStatus(e instanceof Error?e.message:'เข้าร่วมไม่สำเร็จ')}finally{setBusy(false)}}
 const leave=async()=>{if(!confirm('ยืนยันออกจากนัดนี้?'))return;setStatus('');setBusy(true);try{await api.leaveMatch(m.id);await loadPlayers();refresh();setStatus('ออกจากนัดแล้ว ✓')}catch(e){setStatus(e instanceof Error?e.message:'ออกจากนัดไม่สำเร็จ')}finally{setBusy(false)}}
 const remove=async(id:number)=>{if(!confirm('นำสมาชิกคนนี้ออกจากนัด?'))return;setStatus('');setBusy(true);try{await api.removePlayer(m.id,id);await loadPlayers();refresh();setStatus('นำสมาชิกออกจากนัดแล้ว ✓')}catch(e){setStatus(e instanceof Error?e.message:'นำสมาชิกออกไม่สำเร็จ')}finally{setBusy(false)}}
 return <article className="match-card" style={{marginBottom:12}}><div className="match-icon">⚽</div><div style={{flex:1}}><h3>{m.title}</h3><p>{m.match_date}  •  {m.start_time}  •  {m.venue_name}</p><div className="avatars">👥 {m.players}/{m.max_players} คน</div>{status&&<div className="auth-error" role="status" style={{marginTop:8}}>{status}</div>}{show&&<div className="panel" style={{marginTop:8}}><b>สมาชิกในนัด</b>{players.map(p=><div key={p.id} style={{display:'flex',justifyContent:'space-between',gap:8,padding:'6px 0'}}><span>{p.name}{p.owner?' (เจ้าของ)':''}</span>{isOwner&&!p.owner&&<button onClick={()=>remove(p.id)} disabled={busy}>นำออก</button>}</div>)}</div>}</div><div><button onClick={()=>{setShow(!show);if(!show)void loadPlayers()}}>สมาชิก</button>{isOwner?<button disabled>คุณเป็นเจ้าของนัด</button>:players.some(p=>user&&p.id===user.id)?<button disabled={busy} onClick={leave}>ออกจากนัด</button>:<button disabled={busy||state==='expired'||m.players>=m.max_players||!m.open_for_join} onClick={join}>{state==='expired'?'หมดเวลา':m.players>=m.max_players?'เต็ม':!m.open_for_join?'ปิดรับคน':'เข้าร่วม'}</button>}</div></article>
}
function CreateMatchPage({user}:{user:User|null}){const [rows,setRows]=useState<BookingRow[]>([]),[selected,setSelected]=useState<BookingRow|null>(null);useEffect(()=>{if(!user)return;const load=()=>api.bookings().then(setRows).catch(()=>setRows([]));void load();const onChanged=()=>void load();window.addEventListener('porsball:data-changed',onChanged);return()=>window.removeEventListener('porsball:data-changed',onChanged)},[user]);if(!user)return <section className="page"><p className="eyebrow">CREATE MATCH</p><h1>สร้างนัด</h1><div className="panel">กรุณาเข้าสู่ระบบก่อน เพื่อสร้างนัดจากสนามที่คุณจอง</div></section>;return <section className="page"><p className="eyebrow">CREATE MATCH</p><h1>สร้างนัด</h1><p>เลือกสนามและเวลาที่คุณจองไว้ แล้วเปิดรับเพื่อนได้ทันที</p>{rows.length?rows.map(r=>{const state=bookingState(r.booking_date,r.start_time,r.end_time);return <div className="panel booking-row" key={r.id}><div><h3>{r.venue_name}</h3><p>{r.booking_date}  •  {r.start_time}–{r.end_time}</p><b>฿{r.total_price.toLocaleString()}</b>{state==='expired'&&<strong className="expired-label">เลยเวลาจอง</strong>}</div><button className="primary" disabled={state==='expired'} onClick={()=>setSelected(r)}>{state==='expired'?'เลยเวลาจอง':'สร้างนัดจากการจองนี้'}</button></div>}):<div className="panel">ยังไม่มีการจองสนาม กรุณาจองสนามก่อนสร้างนัด</div>}{selected&&<CreateMatch booking={selected} close={()=>setSelected(null)} done={()=>{setSelected(null);api.bookings().then(setRows).catch(()=>setRows([]))}}/>}</section>}
function CreateMatch({booking,close,done}:{booking:BookingRow;close:()=>void;done:()=>void}){const [title,setTitle]=useState('Friendly Match'),[maxPlayers,setMaxPlayers]=useState(10),[busy,setBusy]=useState(false),[error,setError]=useState('');const total=booking.total_price;const fee=Math.ceil(total/Math.max(1,maxPlayers));const submit=async()=>{setError('');const cleanTitle=title.trim();if(!cleanTitle){setError('กรุณาระบุชื่อนัด');return}if(maxPlayers<2||maxPlayers>30){setError('จำนวนผู้เล่นต้องอยู่ระหว่าง 2–30 คน');return}setBusy(true);try{await api.createMatch(booking.id,cleanTitle,fee,maxPlayers);window.dispatchEvent(new Event('porsball:data-changed'));done()}catch(e){setError(e instanceof Error?e.message:'เปิดหาคนไม่สำเร็จ')}finally{setBusy(false)}};return <div className="auth-overlay"><div className="auth-box"><button className="auth-x" onClick={close}>×</button><h2>เปิดหาคน</h2><p>{booking.venue_name}  •  {booking.booking_date}  •  {booking.start_time}–{booking.end_time}</p><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="ชื่อนัด"/><label>จำนวนผู้เล่นทั้งหมด<input type="number" min="2" max="30" value={maxPlayers} onChange={e=>setMaxPlayers(Math.max(2,Math.min(30,Number(e.target.value)||2)))}/></label><p>ค่าสนาม ฿{total.toLocaleString()}  •  คนละประมาณ ฿{fee.toLocaleString()}</p><div className="auth-error">{error}</div><button className="auth-submit" disabled={busy} onClick={submit}>{busy?'กำลังเปิด...':'เปิดหาคน'}</button></div></div>}
function Profile({user,onLogout}:{user:User|null;onLogout:()=>void}){if(!user)return <section className="page"><h1>โปรไฟล์</h1><div className="panel">กรุณาเข้าสู่ระบบเพื่อดูโปรไฟล์</div></section>;const roleLabel=user.role==='admin'?'แอดมิน':user.role==='owner'?'เจ้าของสนาม':'ผู้ใช้';return <section className="page"><div className="profile-head"><div className="avatar">{user.name.charAt(0).toUpperCase()}</div><div><p className="eyebrow">PROFILE</p><h1>{user.name}</h1><p>{user.email}</p></div><button onClick={onLogout}>ออกจากระบบ</button></div><div className="stats"><div><b>{user.wins+user.losses}</b><span>นัด</span></div><div><b>{user.wins}</b><span>ชนะ</span></div><div><b>{user.points}</b><span>แต้ม</span></div><div><b>{roleLabel}</b><span>บทบาท</span></div></div></section>}
function Bookings(){const [rows,setRows]=useState<BookingRow[]|null>(null),[splitFor,setSplitFor]=useState<BookingRow|null>(null),[openFor,setOpenFor]=useState<BookingRow|null>(null),[busy,setBusy]=useState<number|null>(null),[matchBusy,setMatchBusy]=useState<number|null>(null),[status,setStatus]=useState('');
const load=()=>api.bookings().then(setRows).catch(()=>setRows([]));
useEffect(()=>{void load();const onChanged=()=>void load();window.addEventListener('porsball:data-changed',onChanged);return()=>window.removeEventListener('porsball:data-changed',onChanged)},[]);
const cancel=async(id:number)=>{if(!confirm('ยืนยันยกเลิกการจองสนามนี้?'))return;setStatus('');setBusy(id);try{await api.cancelBooking(id);await load();window.dispatchEvent(new Event('porsball:data-changed'));setStatus('ยกเลิกการจองสนามแล้ว ✓')}catch(e){setStatus(e instanceof Error?e.message:'ยกเลิกการจองไม่สำเร็จ')}finally{setBusy(null)}};
const toggleMatch=async(r:BookingRow)=>{if(!r.match_id)return;setStatus('');setMatchBusy(r.id);try{if(r.open_for_join){await api.closeMatch(r.match_id);setStatus('ปิดรับคนในนัดแล้ว ✓')}else{await api.openMatch(r.match_id);setStatus('เปิดรับคนในนัดแล้ว ✓')}await load();window.dispatchEvent(new Event('porsball:data-changed'))}catch(e){setStatus(e instanceof Error?e.message:'เปลี่ยนสถานะนัดไม่สำเร็จ')}finally{setMatchBusy(null)}};
return <section className="page"><p className="eyebrow">MY BOOKINGS</p><h1>การจองของฉัน</h1>{status&&<div className="auth-error" role="status" style={{marginBottom:12}}>{status}</div>}{rows===null?<div className="panel">กำลังโหลด...</div>:rows.length?rows.map(r=>{const state=bookingState(r.booking_date,r.start_time,r.end_time);const hasMatch=!!r.match_id;return <div className="panel booking-row" key={r.id}><div><h3>{r.venue_name}</h3><p>{r.booking_date}  •  {r.start_time}–{r.end_time}</p><b>฿{r.total_price.toLocaleString()}</b>{state==='expired'&&<strong className="expired-label">เลยเวลาจอง</strong>}{state==='active'&&<strong className="active-label">กำลังใช้งาน</strong>}{hasMatch&&state==='upcoming'&&<strong className={r.open_for_join?'active-label':'expired-label'}>{r.open_for_join?'เปิดรับคนอยู่':'ปิดรับคนแล้ว'}</strong>}</div><div className="manage-actions">{state==='upcoming'&&(hasMatch?<button className="primary" disabled={matchBusy===r.id} onClick={()=>toggleMatch(r)}>{matchBusy===r.id?'กำลังเปลี่ยน...':r.open_for_join?'ปิดรับคน':'เปิดรับคน'}</button>:<button className="primary" onClick={()=>setOpenFor(r)}>เปิดหาคน</button>)}<button className="primary" disabled={state==='expired'} onClick={()=>setSplitFor(r)}>หารค่าใช้จ่าย</button>{state==='upcoming'&&<button className="danger" disabled={busy===r.id} onClick={()=>cancel(r.id)}>{busy===r.id?'กำลังยกเลิก...':'ยกเลิกการจอง'}</button>}</div></div>}):<div className="panel">ยังไม่มีประวัติการจอง</div>}{openFor&&<CreateMatch booking={openFor} close={()=>setOpenFor(null)} done={()=>{setOpenFor(null);load()}}/>}{splitFor&&<SplitModal booking={splitFor} close={()=>setSplitFor(null)} afterClose={()=>{setSplitFor(null);load()}}/>}</section>}
function SplitModal({booking,close,afterClose}:{booking:BookingRow;close:()=>void;afterClose:()=>void}){
 const [count,setCount]=useState(5),[names,setNames]=useState<string[]>(Array(5).fill('')),[bill,setBill]=useState<SplitBill|null>(null),[links,setLinks]=useState<{memberId:number;name:string;url:string}[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true)
 useEffect(()=>{api.splitForBooking(booking.id).then(b=>{setBill(b);setCount(b.share_count);setNames(b.members.map(m=>m.name))}).catch(()=>{}).finally(()=>setLoading(false))},[booking.id])
 const resize=(n:number)=>{setCount(n);setNames(prev=>Array.from({length:n},(_,i)=>prev[i]||''))}
 const save=async()=>{setError('');const cleanNames=names.map(n=>n.trim());if(cleanNames.some(n=>!n)){setError('กรุณากรอกชื่อสมาชิกให้ครบทุกคน');return}if(new Set(cleanNames.map(n=>n.toLowerCase())).size!==cleanNames.length){setError('ชื่อสมาชิกต้องไม่ซ้ำกัน');return}setBusy(true);try{const r=await api.createSplit(booking.id,count,cleanNames);setBill(await api.split(r.id))}catch(e){setError(e instanceof Error?e.message:'บันทึกบิลไม่สำเร็จ')}finally{setBusy(false)}}
 const refresh=async(id:number)=>setBill(await api.split(id))
 const makeLinks=async()=>{if(!bill)return;setBusy(true);setError('');try{const r=await api.shareLinks(bill.id);setLinks(r.links.map(x=>({...x,url:`${window.location.origin}/split/${x.token}`})))}catch(e){setError(e instanceof Error?e.message:'สร้างลิงก์แชร์ไม่สำเร็จ')}finally{setBusy(false)}}
 const copy=async(text:string)=>{try{await navigator.clipboard.writeText(text)}catch{setError('ไม่สามารถคัดลอกได้ กรุณาคัดลอกลิงก์ด้วยตนเอง')}}
 const closeBill=async()=>{if(!bill)return;const unpaid=bill.members.filter(m=>!m.paid).length;if(unpaid){setError('ยังมีสมาชิกที่ยังไม่จ่าย '+unpaid+' คน');return}setBusy(true);setError('');try{await api.closeSplit(bill.id);window.dispatchEvent(new Event('porsball:data-changed'));afterClose()}catch(e){setError(e instanceof Error?e.message:'ปิดบิลไม่สำเร็จ')}finally{setBusy(false)}}
 if(loading)return <div className="auth-overlay"><div className="auth-box split-box"><button className="auth-x" onClick={close}>×</button><h2>กำลังโหลดบิล...</h2></div></div>
 return <div className="auth-overlay"><div className="auth-box split-box"><button className="auth-x" onClick={close}>×</button><div className="auth-logo"><b>Pors</b><span>Ball</span> ⚽</div><h2>หารค่าใช้จ่าย</h2><p>{booking.venue_name}  •  รวม ฿{booking.total_price.toLocaleString()}</p>
 {!bill?<><label>จำนวนคน</label><input type="number" min="2" max="30" value={count} onChange={e=>resize(Math.max(2,Math.min(30,Number(e.target.value)||2)))}/><div className="split-names">{names.map((n,i)=><input key={i} value={n} onChange={e=>setNames(prev=>prev.map((x,j)=>j===i?e.target.value:x))} placeholder={'ชื่อคนที่ '+(i+1)}/>)}</div><div className="split-preview">รวม ฿{booking.total_price.toLocaleString()} • เฉลี่ยประมาณ <b>฿{Math.floor(booking.total_price/count).toLocaleString()}</b></div><div className="auth-error">{error}</div><button className="auth-submit" disabled={busy} onClick={save}>{busy?'กำลังบันทึก...':'สร้างและบันทึกบิล'}</button></>
 :<><div className="split-preview">ยอดต่อคน <b>฿{bill.members.length?Math.min(...bill.members.map(m=>m.amount)).toLocaleString():bill.share_amount.toLocaleString()}–฿{bill.members.length?Math.max(...bill.members.map(m=>m.amount)).toLocaleString():bill.share_amount.toLocaleString()}</b>  •  {bill.members.filter(m=>m.paid).length}/{bill.share_count} คนจ่ายแล้ว</div><div className="split-members">{bill.members.map(m=><div className="split-member" key={m.id}><span>{m.name} <b>฿{m.amount.toLocaleString()}</b></span><button disabled={!!m.paid||busy} onClick={async()=>{await api.markPaid(bill.id,m.id);await refresh(bill.id)}}>{m.paid?'จ่ายแล้ว ✓':'ทำเครื่องหมายว่าจ่ายแล้ว'}</button></div>)}</div><button className="auth-submit" disabled={busy} onClick={()=>refresh(bill.id)}>{busy?'กำลังโหลด...':'รีเฟรชสถานะการจ่าย'}</button><button className="auth-submit" disabled={busy||bill.members.some(m=>!m.paid)} onClick={closeBill}>{bill.members.some(m=>!m.paid)?'ปิดบิลได้เมื่อจ่ายครบทุกคน':'ปิดบิล ✓'}</button><div className="auth-error">{error}</div><button className="auth-toggle" disabled={busy} onClick={makeLinks}>{busy?'กำลังสร้างลิงก์...':'สร้างลิงก์ให้สมาชิก'}</button>{links.length>0&&<div className="split-members"><b>ลิงก์ชำระเงินแยกตามสมาชิก</b>{links.map(x=><div className="split-member" key={x.memberId}><span>{x.name}</span><button type="button" onClick={()=>void copy(x.url)}>คัดลอกลิงก์</button><small style={{display:'block',wordBreak:'break-all'}}>{x.url}</small></div>)}</div>}</>}
 </div></div>
}
function SplitGuestPage({token}:{token:string}){
 const [bill,setBill]=useState<Awaited<ReturnType<typeof api.splitGuest>>|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false)
 const load=async()=>{try{setBill(await api.splitGuest(token))}catch(e){setBill(null);setError(e instanceof Error?e.message:'ไม่พบลิงก์ชำระเงิน')}finally{setLoading(false)}}
 useEffect(()=>{let active=true;api.splitGuest(token).then(data=>{if(active)setBill(data)}).catch(e=>{if(active){setBill(null);setError(e instanceof Error?e.message:'ไม่พบลิงก์ชำระเงิน')}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[token])
 const pay=async()=>{setBusy(true);setError('');try{await api.payGuest(token);setDone(true);await load()}catch(e){setError(e instanceof Error?e.message:'ยืนยันการจ่ายไม่สำเร็จ')}finally{setBusy(false)}}
 return <div className="app"><main className="page"><div className="auth-box split-box" style={{margin:'40px auto',maxWidth:520}}><div className="auth-logo"><b>Pors</b><span>Ball</span> ⚽</div><h1>ชำระค่าใช้จ่าย</h1>{loading?<div className="panel" role="status">กำลังโหลดบิล...</div>:bill?<><p>{bill.venue_name} • {bill.booking_date} • {bill.start_time}–{bill.end_time}</p><div className="split-preview"><b>{bill.name}</b><br/>ยอดที่ต้องจ่าย <b>฿{bill.amount.toLocaleString()}</b></div>{bill.paid||done?<div className="panel" role="status"><b>ชำระแล้ว ✓</b><p>รายการนี้ได้รับการยืนยันแล้ว</p></div>:<><div className="auth-error">{error}</div><button className="auth-submit" disabled={busy} onClick={pay}>{busy?'กำลังยืนยัน...':'ฉันจ่ายแล้ว'}</button></>}</>:<div className="panel" role="alert"><b>ไม่สามารถเปิดลิงก์นี้ได้</b><p>{error||'ลิงก์อาจหมดอายุหรือไม่ถูกต้อง'}</p><button className="auth-submit" onClick={()=>void load()}>ลองใหม่</button></div>}</div></main></div>
}
function Auth({close,onUser}:{close:()=>void;onUser:(u:User)=>void}){
 const [mode,setMode]=useState<'register'|'login'|'forgot'|'reset'>('register'),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[code,setCode]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[devCode,setDevCode]=useState('')
 const submit=async()=>{setError('');if(!email||!password||(mode==='register'&&!name)){setError('กรุณากรอกข้อมูลให้ครบ');return}setBusy(true);try{const r=mode==='register'?await api.register(name,email,password):await api.login(email,password);localStorage.setItem('porsball_token',r.token);onUser(r.user);close()}catch(e){setError(e instanceof Error?e.message:'ไม่สามารถเชื่อมต่อเซิร์ฟเวอร์ได้')}finally{setBusy(false)}}
 const sendCode=async()=>{setError('');setDevCode('');if(!email){setError('กรุณากรอกอีเมล');return}setBusy(true);try{const r=await api.forgotPassword(email);setDevCode(r.devCode||'');setMode('reset')}catch(e){setError(e instanceof Error?e.message:'ไม่สามารถส่งรหัสได้')}finally{setBusy(false)}}
 const reset=async()=>{setError('');if(!email||!/^[0-9]{6}$/.test(code)||password.length<8){setError('กรุณากรอก OTP 6 หลัก และรหัสผ่านใหม่อย่างน้อย 8 ตัวอักษร');return}setBusy(true);try{await api.resetPassword(email,code,password);setError('เปลี่ยนรหัสผ่านเรียบร้อยแล้ว ✓');setMode('login');setPassword('');setCode('');setDevCode('')}catch(e){setError(e instanceof Error?e.message:'เปลี่ยนรหัสผ่านไม่สำเร็จ')}finally{setBusy(false)}}
 if(mode==='forgot'||mode==='reset') return <div className="auth-overlay"><div className="auth-box"><button className="auth-x" onClick={close}>×</button><div className="auth-logo"><b>Pors</b><span>Ball</span> ⚽</div>{mode==='forgot'?<><h2>ลืมรหัสผ่าน</h2><p>กรอกอีเมลที่ใช้สมัคร เราจะส่งรหัสยืนยันให้</p><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="อีเมล"/><div className="auth-error">{error}</div><button className="auth-submit" disabled={busy} onClick={sendCode}>{busy?'กำลังส่ง...':'ส่งรหัสยืนยัน'}</button><button className="auth-toggle" onClick={()=>{setMode('login');setError('')}}>กลับเข้าสู่ระบบ</button></>:<><h2>ยืนยันและตั้งรหัสผ่านใหม่</h2><p>ส่งรหัสไปที่ {email}</p>{devCode&&<p className="auth-error">โหมดทดสอบ: OTP คือ {devCode}</p>}<input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" placeholder="รหัสยืนยัน 6 หลัก"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="รหัสผ่านใหม่ (อย่างน้อย 8 ตัวอักษร)"/><div className="auth-error">{error}</div><button className="auth-submit" disabled={busy} onClick={reset}>{busy?'กำลังเปลี่ยน...':'เปลี่ยนรหัสผ่าน'}</button><button className="auth-toggle" onClick={()=>{setMode('forgot');setError('')}}>ส่งรหัสใหม่</button></>}</div></div>
 return <div className="auth-overlay"><div className="auth-box"><button className="auth-x" onClick={close}>×</button><div className="auth-logo"><b>Pors</b><span>Ball</span> ⚽</div><h2>{mode==='register'?'สมัครสมาชิก':'เข้าสู่ระบบ'}</h2><p>{mode==='register'?'สร้างบัญชีเพื่อจองสนามและหาเพื่อนร่วมทีม':'ยินดีต้อนรับกลับมา'}</p>{mode==='register'&&<input value={name} onChange={e=>setName(e.target.value)} placeholder="ชื่อของคุณ"/>}<input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="อีเมล"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="รหัสผ่าน"/><div className="auth-error">{error}</div><button className="auth-submit" disabled={busy} onClick={submit}>{busy?'กำลังดำเนินการ...':mode==='register'?'สมัครสมาชิก':'เข้าสู่ระบบ'}</button>{mode==='login'&&<button className="auth-toggle" onClick={()=>{setMode('forgot');setError('')}}>ลืมรหัสผ่าน?</button>}<button className="auth-toggle" onClick={()=>{setMode(mode==='register'?'login':'register');setError('')}}>{mode==='register'?'มีบัญชีแล้ว? เข้าสู่ระบบ':'ยังไม่มีบัญชี? สมัครสมาชิก'}</button></div></div>
}