import {useEffect,useState} from 'react'
import {api} from './api'
import type {User} from './api'

export default function Friends({user}:{user:User|null}){
 const [q,setQ]=useState(''),[results,setResults]=useState<any[]>([]),[data,setData]=useState<any>(null),[teams,setTeams]=useState<any[]>([]),[team,setTeam]=useState<any>(null),[newTeam,setNewTeam]=useState(''),[msg,setMsg]=useState('')
 const load=()=>{if(!user)return;void api.friends().then(setData).catch(()=>setData(null));void api.teams().then(setTeams).catch(()=>setTeams([]))}
 useEffect(()=>{load()},[user])
 if(!user)return <section className="page"><h1>เพื่อนและทีม</h1><div className="panel">กรุณาเข้าสู่ระบบก่อน</div></section>
 const search=()=>{setMsg('');if(q.trim().length<2){setResults([]);return}void api.searchUsers(q.trim()).then(setResults).catch(e=>setMsg(e.message))}
 return <section className="page"><p className="eyebrow">COMMUNITY</p><h1>เพื่อน & ทีม</h1><p>ค้นหาเพื่อน สร้างทีมประจำ และจัดการสมาชิกในทีม</p>{msg&&<div className="auth-error">{msg}</div>}
  <div className="panel"><h2>ค้นหาเพื่อน</h2><div className="search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ค้นหาด้วยชื่อ"/><button type="button" onClick={search}>ค้นหา</button></div>{results.map(x=><div className="booking-row" key={x.id}><div><b>{x.name}</b><p>{x.age!=null?'อายุ '+x.age+' ปี':'อายุไม่ระบุ'} · {x.position||'ไม่ระบุตำแหน่ง'} · {x.skill_level||'เริ่มต้น'}</p></div><button type="button" onClick={()=>api.sendFriendRequest(x.id).then(()=>setMsg('ส่งคำขอเป็นเพื่อนแล้ว')).catch(e=>setMsg(e.message))}>เพิ่มเพื่อน</button></div>)}</div>
  <div className="panel"><h2>คำขอเป็นเพื่อน</h2>{data?.incoming?.length?data.incoming.map((x:any)=><div className="booking-row" key={x.id}><div><b>{x.name}</b><p>{x.age!=null?'อายุ '+x.age+' ปี':''}</p></div><div><button type="button" onClick={()=>api.respondFriendRequest(x.id,'accept').then(load)}>รับ</button> <button type="button" onClick={()=>api.respondFriendRequest(x.id,'reject').then(load)}>ปฏิเสธ</button></div></div>):<p>ไม่มีคำขอใหม่</p>}</div>
  <div className="panel"><h2>เพื่อนของฉัน ({data?.friends?.length||0})</h2>{data?.friends?.length?data.friends.map((x:any)=><div className="booking-row" key={x.id}><div><b>{x.name}</b><p>{x.position||'ไม่ระบุตำแหน่ง'} · {x.skill_level||'เริ่มต้น'} · {x.points||0} Points</p></div><button type="button" onClick={()=>api.removeFriend(x.id).then(load)}>ลบเพื่อน</button></div>):<p>ยังไม่มีเพื่อนในระบบ</p>}</div>
  <div className="panel"><h2>ทีมของฉัน</h2><div className="search"><input value={newTeam} onChange={e=>setNewTeam(e.target.value)} placeholder="ชื่อทีมใหม่"/><button type="button" onClick={()=>api.createTeam(newTeam).then(()=>{setNewTeam('');load()}).catch(e=>setMsg(e.message))}>สร้างทีม</button></div>{teams.map(t=><button type="button" className="panel" key={t.id} onClick={()=>api.team(t.id).then(setTeam).catch(e=>setMsg(e.message))}><b>{t.name}</b><span>สมาชิก {t.member_count} คน</span></button>)}</div>
  {team&&<div className="modal"><div className="auth-box"><button className="auth-x" type="button" onClick={()=>setTeam(null)}>×</button><p className="eyebrow">TEAM</p><h2>{team.name}</h2>{team.members.map((m:any)=><div className="booking-row" key={m.id}><div><b>{m.name}{m.id===team.owner_id?' 👑':''}</b><p>{m.position||'ไม่ระบุตำแหน่ง'} · {m.skill_level||'เริ่มต้น'}</p></div>{m.id!==team.owner_id&&team.owner_id===user.id&&<button type="button" onClick={()=>api.removeTeamMember(team.id,m.id).then(()=>api.team(team.id).then(setTeam))}>นำออก</button>}</div>)}{team.owner_id===user.id&&<div className="panel"><p>เพิ่มสมาชิกได้จากเพื่อนของคุณโดยใช้ User ID</p><div className="search"><input id="team-user-id" inputMode="numeric" placeholder="User ID"/><button type="button" onClick={()=>{const v=Number((document.getElementById('team-user-id') as HTMLInputElement)?.value);api.addTeamMember(team.id,v).then(()=>api.team(team.id).then(setTeam)).catch(e=>setMsg(e.message))}}>เพิ่ม</button></div></div>}</div></div>}
 </section>
}
