import {useEffect,useState} from 'react'
import {api} from './api'
import type {User} from './api'

export default function Friends({user}:{user:User|null}){
 const [q,setQ]=useState(''),[results,setResults]=useState<any[]>([]),[data,setData]=useState<any>(null),[teams,setTeams]=useState<any[]>([]),[team,setTeam]=useState<any>(null),[teamStats,setTeamStats]=useState<any>(null),[newTeam,setNewTeam]=useState(''),[editName,setEditName]=useState(''),[msg,setMsg]=useState('')
 const load=()=>{if(!user)return;void api.friends().then(setData).catch(()=>setData(null));void api.teams().then(setTeams).catch(()=>setTeams([]))}
 useEffect(()=>{if(!user)return;void api.friends().then(setData).catch(()=>setData(null));void api.teams().then(setTeams).catch(()=>setTeams([]))},[user])
 if(!user)return <section className="page"><h1>เน€เธเธทเนเธญเธเนเธฅเธฐเธ—เธตเธก</h1><div className="panel">เธเธฃเธธเธ“เธฒเน€เธเนเธฒเธชเธนเนเธฃเธฐเธเธเธเนเธญเธ</div></section>
 const search=()=>{setMsg('');if(q.trim().length<2){setResults([]);return}void api.searchUsers(q.trim()).then(setResults).catch(e=>setMsg(e.message))}
 const openTeam=(id:number)=>{setMsg('');void Promise.all([api.team(id),api.teamStats(id)]).then(([detail,stats])=>{setTeam(detail);setEditName(detail.name);setTeamStats(stats)}).catch(e=>setMsg(e.message))}
 const closeTeam=()=>{setTeam(null);setTeamStats(null)}
 const saveTeam=()=>{if(!team)return;void api.updateTeam(team.id,editName.trim()).then(t=>{setMsg('เธเธฑเธเธ—เธถเธเธเธทเนเธญเธ—เธตเธกเนเธฅเนเธง');setTeam((x:any)=>({...x,name:t.name}));setTeams(x=>x.map(v=>v.id===t.id?t:v))}).catch(e=>setMsg(e.message))}
 const removeTeam=()=>{if(!team||!window.confirm('เธ•เนเธญเธเธเธฒเธฃเธฅเธเธ—เธตเธกเธเธตเนเธซเธฃเธทเธญเนเธกเน?'))return;void api.deleteTeam(team.id).then(()=>{setMsg('เธฅเธเธ—เธตเธกเนเธฅเนเธง');closeTeam();load()}).catch(e=>setMsg(e.message))}
 return <section className="page"><p className="eyebrow">COMMUNITY</p><h1>เน€เธเธทเนเธญเธ & เธ—เธตเธก</h1><p>เธเนเธเธซเธฒเน€เธเธทเนเธญเธ เธชเธฃเนเธฒเธเธ—เธตเธกเธเธฃเธฐเธเธณ เนเธฅเธฐเธ”เธนเธเธฅเธเธฒเธเธ—เธตเธกเธเธญเธเธเธธเธ“</p>{msg&&<div className="auth-error">{msg}</div>}
  <div className="panel"><h2>เธเนเธเธซเธฒเน€เธเธทเนเธญเธ</h2><div className="search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="เธเนเธเธซเธฒเธ”เนเธงเธขเธเธทเนเธญ"/><button type="button" onClick={search}>เธเนเธเธซเธฒ</button></div>{results.map(x=><div className="booking-row" key={x.id}><div><b>{x.name}</b><p>{x.age!=null?'เธญเธฒเธขเธธ '+x.age+' เธเธต':'เธญเธฒเธขเธธเนเธกเนเธฃเธฐเธเธธ'} ยท {x.position||'เนเธกเนเธฃเธฐเธเธธเธ•เธณเนเธซเธเนเธ'} ยท {x.skill_level||'เน€เธฃเธดเนเธกเธ•เนเธ'}</p></div><button type="button" onClick={()=>api.sendFriendRequest(x.id).then(()=>setMsg('เธชเนเธเธเธณเธเธญเน€เธเนเธเน€เธเธทเนเธญเธเนเธฅเนเธง')).catch(e=>setMsg(e.message))}>เน€เธเธดเนเธกเน€เธเธทเนเธญเธ</button></div>)}</div>
  <div className="panel"><h2>เธเธณเธเธญเน€เธเนเธเน€เธเธทเนเธญเธ</h2>{data?.incoming?.length?data.incoming.map((x:any)=><div className="booking-row" key={x.id}><div><b>{x.name}</b><p>{x.age!=null?'เธญเธฒเธขเธธ '+x.age+' เธเธต':''}</p></div><div><button type="button" onClick={()=>api.respondFriendRequest(x.id,'accept').then(load)}>เธฃเธฑเธ</button> <button type="button" onClick={()=>api.respondFriendRequest(x.id,'reject').then(load)}>เธเธเธดเน€เธชเธ</button></div></div>):<p>เนเธกเนเธกเธตเธเธณเธเธญเนเธซเธกเน</p>}</div>
  <div className="panel"><h2>เน€เธเธทเนเธญเธเธเธญเธเธเธฑเธ ({data?.friends?.length||0})</h2>{data?.friends?.length?data.friends.map((x:any)=><div className="booking-row" key={x.id}><div><b>{x.name}</b><p>{x.position||'เนเธกเนเธฃเธฐเธเธธเธ•เธณเนเธซเธเนเธ'} ยท {x.skill_level||'เน€เธฃเธดเนเธกเธ•เนเธ'} ยท {x.points||0} Points</p></div><button type="button" onClick={()=>api.removeFriend(x.id).then(load)}>เธฅเธเน€เธเธทเนเธญเธ</button></div>):<p>เธขเธฑเธเนเธกเนเธกเธตเน€เธเธทเนเธญเธเนเธเธฃเธฐเธเธ</p>}</div>
  <div className="panel"><h2>เธ—เธตเธกเธเธญเธเธเธฑเธ</h2><div className="search"><input value={newTeam} onChange={e=>setNewTeam(e.target.value)} placeholder="เธเธทเนเธญเธ—เธตเธกเนเธซเธกเน"/><button type="button" onClick={()=>api.createTeam(newTeam).then(()=>{setNewTeam('');load()}).catch(e=>setMsg(e.message))}>เธชเธฃเนเธฒเธเธ—เธตเธก</button></div>{teams.map(t=><button type="button" className="panel" key={t.id} onClick={()=>openTeam(t.id)}><b>{t.name}</b><span>เธชเธกเธฒเธเธดเธ {t.member_count} เธเธ ยท เธ”เธน Dashboard</span></button>)}</div>
  {team&&<div className="modal"><div className="auth-box"><button className="auth-x" type="button" onClick={closeTeam}>ร—</button><p className="eyebrow">TEAM DASHBOARD</p><div className="team-head"><div><h2>{team.name}</h2><p>Team ID: {team.id} ยท เน€เธเนเธฒเธเธญเธ: {team.owner_id===user.id?'เธเธธเธ“':'เธชเธกเธฒเธเธดเธเธ—เธตเธก'}</p></div>{team.owner_id===user.id&&<div className="manage-actions"><button type="button" onClick={saveTeam}>เธเธฑเธเธ—เธถเธเธเธทเนเธญ</button><button type="button" onClick={removeTeam}>เธฅเธเธ—เธตเธก</button></div>}</div>
   {team.owner_id===user.id&&<div className="search"><input value={editName} onChange={e=>setEditName(e.target.value)} maxLength={50} placeholder="เธเธทเนเธญเธ—เธตเธก"/><button type="button" onClick={saveTeam}>เน€เธเธฅเธตเนเธขเธเธเธทเนเธญ</button></div>}
   {teamStats&&<div className="panel"><div className="stats-grid"><div><b>{teamStats.member_count}</b><span>เธชเธกเธฒเธเธดเธ</span></div><div><b>{teamStats.total_matches}</b><span>เนเธกเธ•เธเนเธ—เธฑเนเธเธซเธกเธ”</span></div><div><b>{teamStats.upcoming_matches}</b><span>เธเธณเธฅเธฑเธเธเธฐเธ–เธถเธ</span></div><div><b>{teamStats.in_progress_matches||0}</b><span>เธเธณเธฅเธฑเธเนเธเนเธ</span></div><div><b>{teamStats.attendance_rate}%</b><span>เธญเธฑเธ•เธฃเธฒเน€เธเนเธฒเธฃเนเธงเธก</span></div><div><b>{teamStats.total_points}</b><span>Points เธฃเธงเธก</span></div></div></div>}
   <div className="panel"><h3>เธเธฅเธเธฒเธเธชเธกเธฒเธเธดเธ</h3>{teamStats?.members?.map((m:any)=><div className="booking-row" key={m.id}><div><b>{m.name}{m.id===team.owner_id?' ๐‘‘':''}</b><p>{m.position||'เนเธกเนเธฃเธฐเธเธธเธ•เธณเนเธซเธเนเธ'} ยท {m.skill_level||'เน€เธฃเธดเนเธกเธ•เนเธ'}</p></div><span>เน€เธเนเธฒเธฃเนเธงเธก {m.attended||0} ยท เนเธกเนเธกเธฒ {m.no_show||0}</span></div>)}</div>
   <div className="panel"><h3>เธเธฃเธฐเธงเธฑเธ•เธดเนเธกเธ•เธเน</h3>{teamStats?.history?.length?teamStats.history.map((m:any)=><div className="booking-row" key={m.id}><div><b>{m.title}</b><p>{m.match_date} ยท {m.start_time}-{m.end_time} ยท {m.venue_name}</p></div><span>{m.state==='UPCOMING'?'เธเธณเธฅเธฑเธเธเธฐเธ–เธถเธ':m.state==='IN_PROGRESS'?'เธเธณเธฅเธฑเธเนเธเนเธ':'เธเธเนเธฅเนเธง'} ยท {m.players}/{m.max_players}</span></div>):<p>เธ—เธตเธกเธขเธฑเธเนเธกเนเธกเธตเธเธฃเธฐเธงเธฑเธ•เธดเนเธกเธ•เธเน</p>}</div>
   <TeamMatchCenter teamId={team.id}/>\n   <div className="panel"><h3>เธชเธกเธฒเธเธดเธเธ—เธตเธก</h3>{team.members.map((m:any)=><div className="booking-row" key={m.id}><div><b>{m.name}{m.id===team.owner_id?' ๐‘‘':''}</b><p>{m.position||'เนเธกเนเธฃเธฐเธเธธเธ•เธณเนเธซเธเนเธ'} ยท {m.skill_level||'เน€เธฃเธดเนเธกเธ•เนเธ'}</p></div>{m.id!==team.owner_id&&team.owner_id===user.id&&<button type="button" onClick={()=>api.removeTeamMember(team.id,m.id).then(()=>openTeam(team.id))}>เธเธณเธญเธญเธ</button>}</div>)}{team.owner_id===user.id&&<div className="panel"><p>เน€เธเธดเนเธกเธชเธกเธฒเธเธดเธเธเธฒเธเน€เธเธทเนเธญเธเธเธญเธเธเธธเธ“เนเธ”เธขเนเธเน User ID</p><div className="search"><input id="team-user-id" inputMode="numeric" placeholder="User ID"/><button type="button" onClick={()=>{const v=Number((document.getElementById('team-user-id') as HTMLInputElement)?.value);api.addTeamMember(team.id,v).then(()=>openTeam(team.id)).catch(e=>setMsg(e.message))}}>เน€เธเธดเนเธก</button></div></div>}</div>
  </div></div>}
 </section>
}
function TeamMatchCenter({teamId}:{teamId:number}){
 const [data,setData]=useState<any>(null),[error,setError]=useState('')
 useEffect(()=>{let active=true;api.teamMatchCenter(teamId).then(x=>{if(active){setData(x);setError('')}}).catch(e=>{if(active)setError(e.message||'Team Match Center load failed')});return()=>{active=false}},[teamId])
 const [players,setPlayers]=useState<Record<number,any[]>>({})
 const showPlayers=async(id:number)=>{try{const r=await api.players(id);setPlayers(x=>({...x,[id]:r.players}))}catch(e){setError(e instanceof Error?e.message:'เนเธซเธฅเธ”เธเธนเนเน€เธฅเนเธเนเธกเนเธชเธณเน€เธฃเนเธ')}}
 if(!data&&!error)return <div className="panel"><p className="eyebrow">TEAM MATCH CENTER</p><p>เธเธณเธฅเธฑเธเนเธซเธฅเธ”เธจเธนเธเธขเนเธเธฅเธฒเธเนเธกเธ•เธเน...</p></div>
 if(error&&!data)return <div className="panel"><p className="eyebrow">TEAM MATCH CENTER</p><p>{error}</p></div>
 return <div className="panel"><p className="eyebrow">TEAM MATCH CENTER</p><h3>เธจเธนเธเธขเนเธเธฅเธฒเธเนเธกเธ•เธเนเธ—เธตเธก</h3>
  <div className="stats-grid"><div><b>{data?.summary?.upcoming||0}</b><span>เธเธฑเธ”เธ–เธฑเธ”เนเธ</span></div><div><b>{data?.summary?.in_progress||0}</b><span>เธเธณเธฅเธฑเธเนเธเนเธ</span></div><div><b>{data?.summary?.pending_invites||0}</b><span>เธฃเธญเธเธฒเธฃเธ•เธญเธเธฃเธฑเธ</span></div><div><b>{data?.summary?.accepted_invites||0}</b><span>เธ•เธญเธเธฃเธฑเธเนเธฅเนเธง</span></div></div>
  {data?.next_match&&<div className="team-match-next"><b>เธเธฑเธ”เธ–เธฑเธ”เนเธ: {data.next_match.title}</b><p>{data.next_match.match_date} ยท {data.next_match.start_time}-{data.next_match.end_time} ยท {data.next_match.venue_name}</p><span>{data.next_match.players}/{data.next_match.max_players} เธเธ ยท เน€เธซเธฅเธทเธญ {data.next_match.spots_left} เธ—เธตเน</span></div>}
  {data?.matches?.length?data.matches.map((m:any)=><div className="booking-row" key={m.id}><div><b>{m.title}</b><p>{m.match_date} ยท {m.start_time}-{m.end_time} ยท {m.venue_name}</p><small>{m.state==='UPCOMING'?'เธเธณเธฅเธฑเธเธเธฐเธ–เธถเธ':'เธเธณเธฅเธฑเธเนเธเนเธ'} ยท {m.players}/{m.max_players} ยท เธฃเธญ {m.pending_invites}</small></div><button type="button" onClick={()=>void showPlayers(m.id)}>เธเธนเนเน€เธฅเนเธ</button>{players[m.id]&&<div className="team-player-list">{players[m.id].map((p:any)=><span key={p.id}>{p.name}{p.owner?' ๐‘‘':''}</span>)}</div>}</div>):<p>เธ—เธตเธกเธขเธฑเธเนเธกเนเธกเธตเนเธกเธ•เธเนเธ—เธตเนเธเธณเธฅเธฑเธเธ”เธณเน€เธเธดเธเธเธฒเธฃเธซเธฃเธทเธญเธเธฑเธ”เธ—เธตเนเธเธณเธฅเธฑเธเธเธฐเธ–เธถเธ</p>}
  {error&&<p className="auth-error">{error}</p>}
 </div>
}

