import {useEffect,useState} from 'react'
import {api} from './api'
import type {User} from './api'

export default function Friends({user}:{user:User|null}){
 const [q,setQ]=useState(''),[results,setResults]=useState<any[]>([]),[data,setData]=useState<any>(null),[teams,setTeams]=useState<any[]>([]),[team,setTeam]=useState<any>(null),[teamStats,setTeamStats]=useState<any>(null),[newTeam,setNewTeam]=useState(''),[editName,setEditName]=useState(''),[msg,setMsg]=useState('')
 const load=()=>{if(!user)return;void api.friends().then(setData).catch(()=>setData(null));void api.teams().then(setTeams).catch(()=>setTeams([]))}
 useEffect(()=>{if(!user)return;void api.friends().then(setData).catch(()=>setData(null));void api.teams().then(setTeams).catch(()=>setTeams([]))},[user])
 if(!user)return <section className="page"><h1>เพื่อนและทีม</h1><div className="panel">กรุณาเข้าสู่ระบบเพื่อใช้งาน Community</div></section>
 const search=()=>{setMsg('');if(q.trim().length<2){setResults([]);return}void api.searchUsers(q.trim()).then(setResults).catch(e=>setMsg(e.message))}
 const openTeam=(id:number)=>{setMsg('');void Promise.all([api.team(id),api.teamStats(id)]).then(([detail,stats])=>{setTeam(detail);setEditName(detail.name);setTeamStats(stats)}).catch(e=>setMsg(e.message))}
 const closeTeam=()=>{setTeam(null);setTeamStats(null)}
 const saveTeam=()=>{if(!team)return;void api.updateTeam(team.id,editName.trim()).then(t=>{setMsg('บันทึกชื่อทีมแล้ว');setTeam((x:any)=>({...x,name:t.name}));setTeams(x=>x.map(v=>v.id===t.id?t:v))}).catch(e=>setMsg(e.message))}
 const removeTeam=()=>{if(!team||!window.confirm('ต้องการลบทีมนี้หรือไม่?'))return;void api.deleteTeam(team.id).then(()=>{setMsg('ลบทีมแล้ว');closeTeam();load()}).catch(e=>setMsg(e.message))}
 return <section className="page"><p className="eyebrow">COMMUNITY</p><h1>เพื่อนและทีม</h1><p>ค้นหาผู้เล่น สร้างทีม และติดตามการเข้าร่วมการแข่งขัน</p>{msg&&<div className="auth-error">{msg}</div>}
  <div className="panel"><h2>ค้นหาผู้เล่น</h2><div className="search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ค้นหาด้วยชื่อหรือข้อมูลผู้เล่น"/><button type="button" onClick={search}>ค้นหา</button></div>{results.map(x=><div className="booking-row" key={x.id}><div><b>{x.name}</b><p>{x.age!=null?`อายุ ${x.age} ปี`:'ไม่ระบุอายุ'} · {x.position||'ไม่ระบุตำแหน่ง'} · {x.skill_level||'ไม่ระบุระดับ'}</p></div><button type="button" onClick={()=>api.sendFriendRequest(x.id).then(()=>setMsg('ส่งคำขอเป็นเพื่อนแล้ว')).catch(e=>setMsg(e.message))}>เพิ่มเพื่อน</button></div>)}</div>
  <div className="panel"><h2>คำขอเป็นเพื่อน</h2>{data?.incoming?.length?data.incoming.map((x:any)=><div className="booking-row" key={x.id}><div><b>{x.name}</b><p>{x.age!=null?`อายุ ${x.age} ปี`:''}</p></div><div><button type="button" onClick={()=>api.respondFriendRequest(x.id,'accept').then(load)}>ยอมรับ</button> <button type="button" onClick={()=>api.respondFriendRequest(x.id,'reject').then(load)}>ปฏิเสธ</button></div></div>):<p>ยังไม่มีคำขอใหม่</p>}</div>
  <div className="panel"><h2>เพื่อนของฉัน ({data?.friends?.length||0})</h2>{data?.friends?.length?data.friends.map((x:any)=><div className="booking-row" key={x.id}><div><b>{x.name}</b><p>{x.position||'ไม่ระบุตำแหน่ง'} · {x.skill_level||'ไม่ระบุระดับ'} · {x.points||0} Points</p></div><button type="button" onClick={()=>api.removeFriend(x.id).then(load)}>ลบเพื่อน</button></div>):<p>ยังไม่มีเพื่อนในระบบ</p>}</div>
  <div className="panel"><h2>ทีมของฉัน</h2><div className="search"><input value={newTeam} onChange={e=>setNewTeam(e.target.value)} placeholder="ชื่อทีม"/><button type="button" onClick={()=>api.createTeam(newTeam).then(()=>{setNewTeam('');load()}).catch(e=>setMsg(e.message))}>สร้างทีม</button></div>{teams.map(t=><button type="button" className="panel" key={t.id} onClick={()=>openTeam(t.id)}><b>{t.name}</b><span>สมาชิก {t.member_count} คน · เปิด Dashboard</span></button>)}</div>
  {team&&<div className="modal"><div className="auth-box"><button className="auth-x" type="button" onClick={closeTeam}>×</button><p className="eyebrow">TEAM DASHBOARD</p><div className="team-head"><div><h2>{team.name}</h2><p>Team ID: {team.id} · {team.owner_id===user.id?'เจ้าของทีม':'สมาชิกทีม'}</p></div>{team.owner_id===user.id&&<div className="manage-actions"><button type="button" onClick={saveTeam}>บันทึก</button><button type="button" onClick={removeTeam}>ลบทีม</button></div>}</div>
   {team.owner_id===user.id&&<div className="search"><input value={editName} onChange={e=>setEditName(e.target.value)} maxLength={50} placeholder="ชื่อทีม"/><button type="button" onClick={saveTeam}>บันทึกชื่อทีม</button></div>}
   {teamStats&&<div className="panel"><div className="stats-grid"><div><b>{teamStats.member_count}</b><span>สมาชิก</span></div><div><b>{teamStats.total_matches}</b><span>การแข่งขันทั้งหมด</span></div><div><b>{teamStats.upcoming_matches}</b><span>นัดถัดไป</span></div><div><b>{teamStats.in_progress_matches||0}</b><span>กำลังแข่ง</span></div><div><b>{teamStats.attendance_rate}%</b><span>อัตราเข้าร่วม</span></div><div><b>{teamStats.total_points}</b><span>คะแนนรวม</span></div></div></div>}
   <div className="panel"><h3>สถิติสมาชิก</h3>{teamStats?.members?.map((m:any)=><div className="booking-row" key={m.id}><div><b>{m.name}{m.id===team.owner_id?' 👑':''}</b><p>{m.position||'ไม่ระบุตำแหน่ง'} · {m.skill_level||'ไม่ระบุระดับ'}</p></div><span>เข้าร่วม {m.attended||0} · ไม่มา {m.no_show||0} · Reliability {m.reliability_score??100}%</span><small>คำเชิญ: รอ {m.invite_pending||0} · รับ {m.invite_accepted||0} · ปฏิเสธ {m.invite_rejected||0}</small></div>)}</div>
   <div className="panel"><h3>ประวัติการแข่งขัน</h3>{teamStats?.history?.length?teamStats.history.map((m:any)=><div className="booking-row" key={m.id}><div><b>{m.title}</b><p>{m.match_date} · {m.start_time}-{m.end_time} · {m.venue_name}</p></div><span>{m.state==='UPCOMING'?'กำลังจะถึง':m.state==='IN_PROGRESS'?'กำลังแข่ง':'จบแล้ว'} · {m.players}/{m.max_players}</span></div>):<p>ยังไม่มีประวัติการแข่งขัน</p>}</div>
   <TeamMatchCenter teamId={team.id} isOwner={team.owner_id===user.id}/>
   <div className="panel"><h3>สมาชิกทีม</h3>{team.members.map((m:any)=><div className="booking-row" key={m.id}><div><b>{m.name}{m.id===team.owner_id?' 👑':''}</b><p>{m.position||'ไม่ระบุตำแหน่ง'} · {m.skill_level||'ไม่ระบุระดับ'}</p></div>{m.id!==team.owner_id&&team.owner_id===user.id&&<button type="button" onClick={()=>api.removeTeamMember(team.id,m.id).then(()=>openTeam(team.id))}>นำออก</button>}</div>)}{team.owner_id===user.id&&<div className="panel"><p>เพิ่มสมาชิกด้วย User ID</p><div className="search"><input id="team-user-id" inputMode="numeric" placeholder="User ID"/><button type="button" onClick={()=>{const v=Number((document.getElementById('team-user-id') as HTMLInputElement)?.value);api.addTeamMember(team.id,v).then(()=>openTeam(team.id)).catch(e=>setMsg(e.message))}}>เพิ่มสมาชิก</button></div></div>}</div>
  </div></div>}
 </section>
}
function TeamMatchCenter({teamId,isOwner}:{teamId:number;isOwner:boolean}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[reminding,setReminding]=useState<number|null>(null),[players,setPlayers]=useState<Record<number,any[]>>({})
 useEffect(()=>{let active=true;api.teamMatchCenter(teamId).then(x=>{if(active){setData(x);setError('')}}).catch(e=>{if(active)setError(e.message||'โหลด Match Center ไม่สำเร็จ')});return()=>{active=false}},[teamId])
 const showPlayers=async(id:number)=>{try{const r=await api.players(id);setPlayers(x=>({...x,[id]:r.players}))}catch(e){setError(e instanceof Error?e.message:'โหลดผู้เล่นไม่สำเร็จ')}}
 const remind=async(matchId:number,userId:number)=>{setReminding(userId);try{await api.teamInviteRemind(teamId,matchId,userId)}catch(e){setError(e instanceof Error?e.message:'ส่งการแจ้งเตือนไม่สำเร็จ')}finally{setReminding(null)}}
 if(!data&&!error)return <div className="panel"><p className="eyebrow">TEAM MATCH CENTER</p><p>กำลังโหลดศูนย์กลางแมตช์ทีม...</p></div>
 if(error&&!data)return <div className="panel"><p className="eyebrow">TEAM MATCH CENTER</p><p>{error}</p></div>
 return <div className="panel"><p className="eyebrow">TEAM MATCH CENTER</p><h3>ศูนย์กลางแมตช์ทีม</h3>
  <div className="stats-grid"><div><b>{data?.summary?.upcoming||0}</b><span>นัดถัดไป</span></div><div><b>{data?.summary?.in_progress||0}</b><span>กำลังแข่ง</span></div><div><b>{data?.summary?.pending_invites||0}</b><span>รอตอบรับ</span></div><div><b>{data?.summary?.accepted_invites||0}</b><span>ตอบรับแล้ว</span></div></div>
  {data?.next_match&&<div className="team-match-next"><b>นัดถัดไป: {data.next_match.title}</b><p>{data.next_match.match_date} · {data.next_match.start_time}-{data.next_match.end_time} · {data.next_match.venue_name}</p><span>{data.next_match.players}/{data.next_match.max_players} คน · เหลือ {data.next_match.spots_left} ที่</span></div>}
  {data?.matches?.length?data.matches.map((m:any)=><div className="booking-row" key={m.id}><div><b>{m.title}</b><p>{m.match_date} · {m.start_time}-{m.end_time} · {m.venue_name}</p><small>{m.state==='UPCOMING'?'กำลังจะถึง':'กำลังแข่ง'} · {m.players}/{m.max_players} · รอ {m.pending_invites}</small></div><button type="button" onClick={()=>void showPlayers(m.id)}>ผู้เล่น</button>
   {players[m.id]&&<div className="team-player-list">{players[m.id].map((p:any)=><span key={p.id}>{p.name}{p.owner?' 👑':''}</span>)}</div>}
   {m.invites?.length>0&&<div className="team-invite-list"><strong>คำเชิญสมาชิก</strong>{m.invites.map((v:any)=><div className="team-invite-row" key={v.id}><span>{v.name}</span><span className="team-invite-status">{v.status==='pending'?'รอตอบรับ':v.status==='accepted'?'ตอบรับแล้ว':'ปฏิเสธแล้ว'}</span>{isOwner&&v.status==='pending'&&<button type="button" disabled={reminding===v.user_id} onClick={()=>void remind(m.id,v.user_id)}>{reminding===v.user_id?'กำลังส่ง...':'ส่งเตือน'}</button>}</div>)}</div>}
  </div>):<p>ทีมยังไม่มีแมตช์ที่กำลังดำเนินการหรือนัดที่กำลังจะถึง</p>}
  {error&&<p className="auth-error">{error}</p>}
 </div>
}
