import {useCallback,useEffect,useState} from 'react'
import {api} from './api'
import type {BookingRow,Match,User} from './api'

function stateOf(r:BookingRow){
 const now=new Date(),from=new Date(`${r.booking_date}T${r.start_time}:00+07:00`),to=new Date(`${r.booking_date}T${r.end_time}:00+07:00`)
 return now>=to?'expired':now>=from?'active':'upcoming'
}
export default function Manage({user}:{user:User|null}){
 const [rows,setRows]=useState<BookingRow[]>([]),[matches,setMatches]=useState<Match[]>([]),[busy,setBusy]=useState<number|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('')
 const load=useCallback(async()=>{if(!user)return;setLoading(true);setError('');try{const [b,m]=await Promise.all([api.bookings(),api.matchesMe()]);setRows(b);setMatches(m)}catch(e){setError(e instanceof Error?e.message:'โหลดข้อมูลไม่สำเร็จ')}finally{setLoading(false)}},[user])
 useEffect(()=>{if(!user)return;const refresh=()=>{if(document.visibilityState!=='visible')return;void load()};refresh();const timer=window.setInterval(refresh,30000);const onFocus=()=>refresh();const onVisible=()=>{if(document.visibilityState==='visible')refresh()};window.addEventListener('focus',onFocus);document.addEventListener('visibilitychange',onVisible);return()=>{window.clearInterval(timer);window.removeEventListener('focus',onFocus);document.removeEventListener('visibilitychange',onVisible)}},[user,load])
 if(!user)return <section className="page"><p className="eyebrow">MANAGE</p><h1>{"\u0e08\u0e31\u0e14\u0e01\u0e32\u0e23\u0e19\u0e31\u0e14"}</h1><div className="panel">{"\u0e01\u0e23\u0e38\u0e13\u0e32\u0e40\u0e02\u0e49\u0e32\u0e2a\u0e39\u0e48\u0e23\u0e30\u0e1a\u0e1a"}</div></section>
 const cancel=async(id:number)=>{if(!window.confirm("ยืนยันยกเลิกการจองนี้?"))return;setBusy(id);setError('');setMessage('');try{await api.cancelBooking(id);await load();window.dispatchEvent(new Event('porsball:data-changed'));setMessage('ยกเลิกการจองแล้ว')}catch(e){setError(e instanceof Error?e.message:'ยกเลิกการจองไม่สำเร็จ')}finally{setBusy(null)}}
 const toggle=async(m:Match)=>{setBusy(m.id);setError('');setMessage('');try{if(m.open_for_join)await api.closeMatch(m.id);else await api.openMatch(m.id);await load();window.dispatchEvent(new Event('porsball:data-changed'));setMessage(m.open_for_join?'ปิดรับคนเข้าร่วมแล้ว':'เปิดรับคนเข้าร่วมแล้ว')}catch(e){setError(e instanceof Error?e.message:'อัปเดตนัดไม่สำเร็จ')}finally{setBusy(null)}}
 return <section className="page"><p className="eyebrow">MANAGE MATCHES</p><h1>{"\u0e08\u0e31\u0e14\u0e01\u0e32\u0e23\u0e19\u0e31\u0e14"}</h1><p>{"\u0e40\u0e1b\u0e34\u0e14-\u0e1b\u0e34\u0e14\u0e23\u0e31\u0e1a\u0e04\u0e19 \u0e41\u0e25\u0e30\u0e22\u0e01\u0e40\u0e25\u0e34\u0e01\u0e01\u0e32\u0e23\u0e08\u0e2d\u0e07"}</p>
 {message&&<div className="panel" role="status" aria-live="polite"><b>{message}</b></div>}{error&&<div className="panel" role="alert" aria-live="assertive"><b>ดำเนินการไม่สำเร็จ</b><p>{error}</p><button type="button" className="confirm" onClick={()=>void load()} disabled={loading} aria-busy={loading}>{loading?'กำลังโหลด...':'ลองอีกครั้ง'}</button></div>}
 {loading&&!rows.length?<div className="panel" role="status" aria-live="polite">กำลังโหลดรายการจอง...</div>:rows.length?rows.map(r=>{const st=stateOf(r),m=matches.find(x=>x.booking_id===r.id);return <div className="panel booking-row" key={r.id} role="group" aria-label={`การจอง ${r.venue_name} ${r.booking_date} ${r.start_time}-${r.end_time}`}><div><h3>{r.venue_name}</h3><p>{r.booking_date} - {r.start_time}-{r.end_time}</p><b>฿{r.total_price.toLocaleString()}</b>{st==='expired'&&<strong className="expired-label">{"\u0e40\u0e25\u0e22\u0e40\u0e27\u0e25\u0e32\u0e08\u0e2d\u0e07"}</strong>}{st==='active'&&<strong className="active-label">{"\u0e01\u0e33\u0e25\u0e31\u0e07\u0e43\u0e0a\u0e49\u0e07\u0e32\u0e19"}</strong>}{m&&<p>Players: {m.players}/{m.max_players} - {m.open_for_join?"\u0e40\u0e1b\u0e34\u0e14\u0e23\u0e31\u0e1a\u0e04\u0e19":"\u0e1b\u0e34\u0e14\u0e23\u0e31\u0e1a\u0e04\u0e19"}</p>}</div><div className="manage-actions">{m&&<button type="button" className="primary" disabled={busy===m.id||st==='expired'} aria-busy={busy===m.id} aria-label={m.open_for_join?"ปิดรับคนเข้าร่วม":"เปิดรับคนเข้าร่วม"} onClick={()=>toggle(m)}>{m.open_for_join?"\u0e1b\u0e34\u0e14\u0e23\u0e31\u0e1a\u0e04\u0e19":"\u0e40\u0e1b\u0e34\u0e14\u0e23\u0e31\u0e1a\u0e04\u0e19"}</button>}{st==='upcoming'&&<button type="button" className="danger" disabled={busy===r.id} aria-busy={busy===r.id} aria-label="ยกเลิกการจองสนาม" onClick={()=>cancel(r.id)}> {"\u0e22\u0e01\u0e40\u0e25\u0e34\u0e01\u0e01\u0e32\u0e23\u0e08\u0e2d\u0e07"}</button>}</div></div>}) : <div className="panel">{"\u0e22\u0e31\u0e07\u0e44\u0e21\u0e48\u0e21\u0e35\u0e01\u0e32\u0e23\u0e08\u0e2d\u0e07"}</div>}
 </section>
}
