import {useCallback,useEffect,useRef,useState} from 'react'
import {api,venueWorkflowApi} from './api'
import type {Facility,Venue,VenueRequest,OwnerBookingRow} from './api'
import './OwnerDashboard.css'

const readImage=(file:File,max=640)=>new Promise<string>((resolve,reject)=>{
 if(!/^image\/(png|jpe?g|webp)$/i.test(file.type)) return reject(new Error('รองรับรูป PNG, JPG หรือ WebP'))
 if(file.size>5*1024*1024) return reject(new Error('รูปต้องมีขนาดไม่เกิน 5 MB'))
 const reader=new FileReader();reader.onerror=()=>reject(new Error('อ่านรูปไม่สำเร็จ'))
 reader.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error('ไฟล์รูปไม่ถูกต้อง'));img.onload=()=>{const scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d')?.drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/webp',.78))};img.src=String(reader.result)};reader.readAsDataURL(file)
})

export default function OwnerDashboard(){
 const [facilities,setFacilities]=useState<Facility[]>([]),[venues,setVenues]=useState<Venue[]>([]),[bookings,setBookings]=useState<OwnerBookingRow[]>([])
 const [requests,setRequests]=useState<VenueRequest[]>([]),[selected,setSelected]=useState<Facility|null>(null),[editing,setEditing]=useState<Venue|null>(null)
 const [showFacility,setShowFacility]=useState(false),[showField,setShowField]=useState<number|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[now,setNow]=useState(()=>Date.now())
 const loadedRef=useRef(false)
 useEffect(()=>{const t=window.setInterval(()=>setNow(Date.now()),30000);return()=>window.clearInterval(t)},[])
 const load=useCallback(async()=>{if(!loadedRef.current)setLoading(true);setError('');try{const [f,v,b,r]=await Promise.all([api.ownerFacilities(),api.ownerVenues(),api.ownerBookings(),venueWorkflowApi.ownerVenueRequests()]);setFacilities(f);setVenues(v);setBookings(b);setRequests(r)}catch(e){setError(e instanceof Error?e.message:'โหลดข้อมูลไม่สำเร็จ')}finally{loadedRef.current=true;setLoading(false)}},[])
 useEffect(()=>{const t=window.setTimeout(()=>void load(),0);const onFocus=()=>void load();window.addEventListener('focus',onFocus);return()=>{window.clearTimeout(t);window.removeEventListener('focus',onFocus)}},[load])
 const statusOf=(v:Venue)=>{if(v.service_status==='maintenance')return 'maintenance';if(v.service_status==='inactive')return 'inactive';const active=bookings.some(b=>b.venue_id===v.id&&String(b.status).toLowerCase()==='confirmed'&&now>=new Date(`${b.booking_date}T${b.start_time}:00+07:00`).getTime()&&now<new Date(`${b.booking_date}T${b.end_time}:00+07:00`).getTime());return active?'busy':'free'}
 const saveField=async()=>{if(!editing)return;setSaving(true);setError('');try{const v=await api.updateOwnerVenue(editing.id,{name:editing.name.trim(),area:editing.area.trim(),address:editing.address.trim(),price_per_hour:editing.price_per_hour,roof:editing.roof,field_types:editing.field_types.trim(),image:editing.image||null,service_status:editing.service_status||'active'});setVenues(x=>x.map(a=>a.id===v.id?v:a));setEditing(null);setMessage('บันทึกข้อมูลสนามแล้ว')}catch(e){setError(e instanceof Error?e.message:'บันทึกสนามไม่สำเร็จ')}finally{setSaving(false)}}
 const facilityFields=(f:Facility)=>venues.filter(v=>v.facility_id===f.id)
 const totalFields=venues.length,activeFields=venues.filter(v=>v.service_status==='active').length,busyFields=venues.filter(v=>statusOf(v)==='busy').length
 return <section className="panel owner-dashboard">
  <div className="section-head"><div><p className="eyebrow">OWNER WORKSPACE</p><h2>จัดการสถานที่และสนาม</h2><p>สร้างสถานที่ของคุณ แล้วเพิ่มสนาม A, B, C, D ได้ในที่เดียว</p></div><div className="owner-head-actions"><button type="button" className="primary" onClick={()=>{setError('');setShowFacility(true)}}>＋ เพิ่มสถานที่</button><button type="button" className="link" onClick={()=>void load()} disabled={loading}>{loading?'กำลังโหลด...':'รีเฟรช'}</button></div></div>
  {message&&<div className="panel owner-success" role="status">{message}</div>}{error&&<div className="panel owner-error" role="alert">{error}</div>}
  {!loading&&<div className="owner-grid"><div className="panel"><b>{facilities.length}</b><span>สถานที่</span></div><div className="panel"><b>{totalFields}</b><span>สนามทั้งหมด</span></div><div className="panel"><b>{activeFields}</b><span>พร้อมบริการ</span></div><div className="panel"><b>{busyFields}</b><span>กำลังมีลูกค้า</span></div></div>}
  {requests.length>0&&<div className="panel owner-review-box"><div className="section-head"><div><h3>สถานะสนามที่รอตรวจสอบ</h3><p>สนามจะเปิดให้ User จองเมื่อ Admin อนุมัติแล้ว</p></div></div>{requests.map(v=><div className="owner-review-row" key={v.id}><div><b>{v.name}</b><small>{v.area} · {v.field_types}</small></div><span className={`review-pill review-${v.review_status}`}>{v.review_status==='pending_review'?'รอตรวจสอบ':v.review_status==='changes_requested'?'ต้องแก้ไข':'ไม่อนุมัติ'}</span>{v.review_note&&<p>{v.review_note}</p>}{v.review_status==='changes_requested'&&<button type="button" className="primary" onClick={()=>setEditing({...v})}>แก้ไขตามหมายเหตุ</button>}</div>)}</div>}
  {loading&&!facilities.length?<div className="panel owner-empty">กำลังโหลดข้อมูลสถานที่...</div>:facilities.length?<div className="facility-list">{facilities.map(f=><FacilityCard key={f.id} facility={f} fields={facilityFields(f)} statusOf={statusOf} onEdit={()=>setSelected(f)} onAddField={()=>setShowField(f.id)} onEditField={v=>setEditing({...v})}/>)}</div>:<div className="panel owner-empty"><b>ยังไม่มีสถานที่</b><p>เริ่มจากเพิ่มชื่อสถานที่ ที่อยู่ และรูปสถานที่ของคุณ</p><button type="button" className="primary" onClick={()=>setShowFacility(true)}>＋ เพิ่มสถานที่แรก</button></div>}
  {showFacility&&<FacilityModal close={()=>setShowFacility(false)} done={async()=>{setShowFacility(false);setMessage('สร้างสถานที่เรียบร้อยแล้ว');await load()}}/>}
  {showField&&<FieldModal facility={facilities.find(f=>f.id===showField)!} close={()=>setShowField(null)} done={async()=>{setShowField(null);setMessage('ส่งสนามให้แอดมินตรวจสอบแล้ว');await load()}}/>}
  {selected&&<FacilityEditModal facility={selected} close={()=>setSelected(null)} done={async()=>{setSelected(null);setMessage('บันทึกข้อมูลสถานที่แล้ว');await load()}}/>}
  {editing&&<FieldEditModal venue={editing} close={()=>setEditing(null)} setVenue={setEditing} save={saveField} saving={saving}/>}
 </section>
}

function FacilityCard({facility,fields,statusOf,onEdit,onAddField,onEditField}:{facility:Facility;fields:Venue[];statusOf:(v:Venue)=>string;onEdit:()=>void;onAddField:()=>void;onEditField:(v:Venue)=>void}){
 const ready=fields.filter(v=>v.review_status==='approved'&&v.service_status==='active').length
 return <article className="panel facility-card"><div className="facility-cover">{facility.image?<img src={facility.image} alt={`รูป ${facility.name}`}/>:<span>🏟️</span>}<div><b>{facility.name}</b><small>📍 {facility.address}</small></div></div><div className="facility-summary"><span><b>{fields.length}</b> สนาม</span><span><b>{ready}</b> พร้อมบริการ</span><span>🟢 ว่าง / 🔴 ใช้งาน</span></div>{facility.description&&<p className="facility-description">{facility.description}</p>}<div className="facility-actions"><button type="button" onClick={onEdit}>แก้ไขข้อมูลสถานที่</button><button type="button" className="primary" onClick={onAddField}>＋ เพิ่มสนามในสถานที่นี้</button></div><div className="field-list"><div className="field-list-head"><h3>สนามในสถานที่</h3><span>{fields.length} สนาม</span></div>{fields.length?fields.map(v=><div className="field-row" key={v.id}>{v.image?<img src={v.image} alt=""/>:<div className="field-thumb">⚽</div>}<div className="field-main"><b>{v.name}</b><small>{v.field_types} · ฿{v.price_per_hour.toLocaleString()}/ชม.</small><small>{statusOf(v)==='busy'?'🔴 กำลังมีลูกค้า':statusOf(v)==='maintenance'?'🟠 ปิดปรับปรุง':statusOf(v)==='inactive'?'⚪ ปิดบริการ':'🟢 ว่าง / พร้อมบริการ'}</small></div><span className={`field-review review-${v.review_status||'approved'}`}>{v.review_status==='approved'?'อนุมัติแล้ว':v.review_status==='pending_review'?'รอตรวจสอบ':v.review_status==='changes_requested'?'ต้องแก้ไข':'ไม่อนุมัติ'}</span><button type="button" onClick={()=>onEditField(v)}>แก้ไข</button></div>):<div className="field-empty">ยังไม่มีสนามในสถานที่นี้</div>}</div></article>
}

function FacilityModal({close,done}:{close:()=>void;done:()=>Promise<void>}){
 const [name,setName]=useState(''),[address,setAddress]=useState(''),[phone,setPhone]=useState(''),[description,setDescription]=useState(''),[image,setImage]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const submit=async()=>{setError('');if(!name.trim()||!address.trim()){setError('กรุณากรอกชื่อสถานที่และที่อยู่');return}setBusy(true);try{await api.createFacility({name:name.trim(),address:address.trim(),phone:phone.trim(),description:description.trim(),image});await done()}catch(e){setError(e instanceof Error?e.message:'สร้างสถานที่ไม่สำเร็จ')}finally{setBusy(false)}}
 return <div className="modal"><div className="booking owner-edit-modal" role="dialog" aria-modal="true"><button type="button" className="close" onClick={close}>×</button><div className="booking-content"><p className="eyebrow">NEW LOCATION</p><h2>เพิ่มสถานที่เตะบอล</h2><p>ข้อมูลนี้จะแสดงให้ User เห็นเป็นชื่อสถานที่และที่ตั้ง</p><label>ชื่อสถานที่เตะบอล<input value={name} onChange={e=>setName(e.target.value)} placeholder="เช่น PorsBall Football Arena"/></label><label>สถานที่ตั้ง / ที่อยู่<textarea value={address} onChange={e=>setAddress(e.target.value)} rows={3} placeholder="เช่น ถนนพระราม 9 กรุงเทพฯ"/></label><label>เบอร์โทร<input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel" placeholder="เบอร์ติดต่อสถานที่"/></label><label>รายละเอียดสถานที่<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={3} placeholder="ที่จอดรถ เวลาเปิด-ปิด หรือรายละเอียดเพิ่มเติม"/></label><ImagePicker value={image} onChange={setImage} label="รูปสถานที่"/><ErrorText text={error}/><button type="button" className="confirm" disabled={busy} onClick={submit}>{busy?'กำลังบันทึก...':'สร้างสถานที่ →'}</button></div></div></div>
}

function FacilityEditModal({facility,close,done}:{facility:Facility;close:()=>void;done:()=>Promise<void>}){
 const [name,setName]=useState(facility.name),[address,setAddress]=useState(facility.address),[phone,setPhone]=useState(facility.phone||''),[description,setDescription]=useState(facility.description||''),[image,setImage]=useState<string|null>(facility.image),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const submit=async()=>{setBusy(true);setError('');try{await api.updateFacility(facility.id,{name:name.trim(),address:address.trim(),phone:phone.trim(),description:description.trim(),image});await done()}catch(e){setError(e instanceof Error?e.message:'บันทึกสถานที่ไม่สำเร็จ')}finally{setBusy(false)}}
 return <div className="modal"><div className="booking owner-edit-modal" role="dialog" aria-modal="true"><button type="button" className="close" onClick={close}>×</button><div className="booking-content"><p className="eyebrow">LOCATION</p><h2>แก้ไขข้อมูลสถานที่</h2><label>ชื่อสถานที่<input value={name} onChange={e=>setName(e.target.value)}/></label><label>สถานที่ตั้ง<textarea value={address} onChange={e=>setAddress(e.target.value)} rows={3}/></label><label>เบอร์โทร<input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>รายละเอียด<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={3}/></label><ImagePicker value={image} onChange={setImage} label="รูปสถานที่"/><ErrorText text={error}/><button type="button" className="confirm" disabled={busy} onClick={submit}>{busy?'กำลังบันทึก...':'บันทึกสถานที่'}</button></div></div></div>
}

function FieldModal({facility,close,done}:{facility:Facility;close:()=>void;done:()=>Promise<void>}){
 const suggestedName=(()=>{const used=new Set(facility.fields.map(v=>v.name.toLowerCase()));for(const x of ['สนาม A','สนาม B','สนาม C','สนาม D','สนาม E','สนาม F'])if(!used.has(x.toLowerCase()))return x;return `สนาม ${facility.fields.length+1}`})()
 const [name,setName]=useState(suggestedName),[price,setPrice]=useState(1200),[fields,setFields]=useState('5v5'),[roof,setRoof]=useState(true),[image,setImage]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const submit=async()=>{setError('');if(!name.trim()||price<=0||!fields.trim()){setError('กรุณากรอกข้อมูลสนามให้ครบ');return}setBusy(true);try{await api.createField(facility.id,{name:name.trim(),area:facility.name,address:facility.address,price_per_hour:price,roof,field_types:fields.trim(),image});await done()}catch(e){setError(e instanceof Error?e.message:'เพิ่มสนามไม่สำเร็จ')}finally{setBusy(false)}}
 return <div className="modal"><div className="booking owner-edit-modal" role="dialog" aria-modal="true"><button type="button" className="close" onClick={close}>×</button><div className="booking-content"><p className="eyebrow">NEW FIELD</p><h2>เพิ่มสนามใน {facility.name}</h2><label>ชื่อสนาม<input value={name} onChange={e=>setName(e.target.value)} placeholder="เช่น สนาม A"/></label><label>ประเภทสนาม<input value={fields} onChange={e=>setFields(e.target.value)} placeholder="5v5 หรือ 7v7, 11v11"/></label><label>ราคาต่อชั่วโมง<input type="number" min="1" value={price} onChange={e=>setPrice(Math.max(1,Number(e.target.value)||1))}/></label><label className="owner-check"><input type="checkbox" checked={roof} onChange={e=>setRoof(e.target.checked)}/> มีหลังคา</label><ImagePicker value={image} onChange={setImage} label="รูปสนาม"/><p className="field-help">ที่อยู่ของสนามจะใช้ที่อยู่ของสถานที่โดยอัตโนมัติ</p><ErrorText text={error}/><button type="button" className="confirm" disabled={busy} onClick={submit}>{busy?'กำลังส่งตรวจสอบ...':'เพิ่มสนามและส่งตรวจสอบ →'}</button></div></div></div>
}

function FieldEditModal({venue,close,setVenue,save,saving}:{venue:Venue;close:()=>void;setVenue:(v:Venue)=>void;save:()=>Promise<void>;saving:boolean}){return <div className="modal"><div className="booking owner-edit-modal" role="dialog" aria-modal="true"><button type="button" className="close" onClick={close}>×</button><div className="booking-content"><p className="eyebrow">FIELD</p><h2>แก้ไข {venue.name}</h2><label>ชื่อสนาม<input value={venue.name} onChange={e=>setVenue({...venue,name:e.target.value})}/></label><label>ประเภทสนาม<input value={venue.field_types} onChange={e=>setVenue({...venue,field_types:e.target.value})}/></label><label>ราคาต่อชั่วโมง<input type="number" min="1" value={venue.price_per_hour} onChange={e=>setVenue({...venue,price_per_hour:Math.max(1,Number(e.target.value)||1)})}/></label><label>ที่อยู่สนาม<textarea value={venue.address} onChange={e=>setVenue({...venue,address:e.target.value})} rows={2}/></label><label className="owner-check"><input type="checkbox" checked={!!venue.roof} onChange={e=>setVenue({...venue,roof:e.target.checked?1:0})}/> มีหลังคา</label><label>สถานะบริการ<select value={venue.service_status||'active'} onChange={e=>setVenue({...venue,service_status:e.target.value as Venue['service_status']})}><option value="active">🟢 พร้อมบริการ</option><option value="maintenance">🟠 ปิดปรับปรุง</option><option value="inactive">⚪ ปิดบริการ</option></select></label><ImagePicker value={venue.image||null} onChange={x=>setVenue({...venue,image:x})} label="รูปสนาม"/><button type="button" className="confirm" disabled={saving||!venue.name.trim()||!venue.address.trim()||venue.price_per_hour<=0} onClick={()=>void save()}>{saving?'กำลังบันทึก...':'บันทึกสนาม'}</button></div></div></div>}

function ImagePicker({value,onChange,label}:{value:string|null;onChange:(x:string|null)=>void;label:string}){const [error,setError]=useState('');return <div className="owner-image-picker"><label>{label}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{onChange(await readImage(f));setError('')}catch(err){setError(err instanceof Error?err.message:'เลือกรูปไม่สำเร็จ')}}}/></label>{value&&<div className="image-preview"><img src={value} alt={`ตัวอย่าง${label}`}/><button type="button" onClick={()=>onChange(null)}>ลบรูป</button></div>}{error&&<small className="image-error">{error}</small>}</div>}
const ErrorText=({text}:{text:string})=>text?<div className="auth-error" role="alert">{text}</div>:null
